
import java.awt.event.KeyEvent;
import java.awt.event.WindowEvent;
import java.awt.event.WindowListener;
import java.util.Calendar;
import javax.swing.JOptionPane;
import lib.jdb.connection.JDBConnection;
import lib.jdb.jdbquery.JDBQuery;
import lib.jdb.jdbquery.event.ErrorEventObject;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author vmf
 */
public class JFEmprestimoLivros extends javax.swing.JFrame {
    String qryLivro ="select concat(t.titulo, \" | \",au.autor,\" | \",a.assunto) as \"livro\" from livro l inner join"
                            + " titulo t on t.id = l.titulo_id inner join assunto a on a.id = t.assunto_id "
                                + " inner join autor au on t.autor_id = au.id ";
    /**
     * Creates new form JFAluno
     */
    public JFEmprestimoLivros() {
        initComponents();
        CustomTable.setDefaulttable(jDBTable2);
        jDBTable2.setFieldsTitle("livro_id", "Tombo");
        jDBTable2.setFieldsTitle("data_devolucao", "Data da Devolução");
        jDBTable2.setFieldsTitle("prazo_devolucao", "Prazo de Devolução");
        jDBQuerySlaveEmpLivros.setShowMessageOnError(false);
        jDBQuerySlaveEmpLivros.addErrorEventListener((ErrorEventObject eeo) -> {
            if(eeo.getErrorCode()==1452){
                JOptionPane.showMessageDialog(null, "Tombo inválido, favor verifique se o tombo consta no cadastro.",
                        "ERRO", JOptionPane.ERROR_MESSAGE);
            }else{
                JOptionPane.showMessageDialog(null, eeo.getErrorMessage(),
                        "ERRO", JOptionPane.ERROR_MESSAGE);
            }
        });
    }
    public JFEmprestimoLivros(JDBConnection jdb, String emp_id) {
        this();
        jDBQuerySlaveUsuario.setJDBConnection(jdb);
        jDBQuerySlaveEmpLivros.setJDBConnection(jdb);
        jDBQueryEmprestimos.setJDBConnection(jdb);
        jDBQueryLivro.setJDBConnection(jdb);
        jDBQueryEmprestimos.setSQL("select * from emprestimo where id = "+emp_id);
        jDBQueryEmprestimos.execQuery();
    }
    public JFEmprestimoLivros(JDBQuery jdbQry) {
        this();
        jDBQuerySlaveUsuario.setJDBConnection(jdbQry.getJDBConnection());
        jDBQuerySlaveEmpLivros.setJDBConnection(jdbQry.getJDBConnection());
        jDBQueryEmprestimos.setJDBConnection(jdbQry.getJDBConnection());
        jDBQueryLivro.setJDBConnection(jdbQry.getJDBConnection());
        jDBQueryEmprestimos.setSQL("select * from emprestimo where id = "+jdbQry.getCurrentFieldValue("id"));
        jDBQueryEmprestimos.execQuery();
    }
    public void atualizaEMps(int id){
        jDBQueryEmprestimos.setSQL("select * from emprestimo where id = "+id);
        jDBQueryEmprestimos.execQuery();
    }
    
    public JFEmprestimoLivros(JDBConnection jdb, int usuarioID) {
        this();
        jDBQuerySlaveUsuario.setJDBConnection(jdb);
        jDBQuerySlaveEmpLivros.setJDBConnection(jdb);
        jDBQueryEmprestimos.setJDBConnection(jdb);
        jDBQueryLivro.setJDBConnection(jdb);
        jDBQueryEmprestimos.setSQL("select * from emprestimo where id=0");
        jDBQueryEmprestimos.execQuery();
        jDBQueryEmprestimos.insert();
        jDBQueryEmprestimos.setNewCurrentFieldValueAsInteger("usuario_id", usuarioID);
        jDBQueryEmprestimos.setNewCurrentFieldValue("data", 
                Calendar.getInstance().getTime().toLocaleString().split(" ")[0]);
        jDBQueryEmprestimos.save();
        setPzDevDefault();
        jDBTextFieldIdLivro.requestFocus();
    }

    private void setPzDevDefault(){
        Calendar c = Calendar.getInstance();
        c.setTime(jDBQueryEmprestimos.getCurrentFieldValueAsSQLDate("data"));
        c.add(Calendar.DAY_OF_MONTH, 7);
        jDBTextFieldPzDev.setText(c.getTime().toLocaleString().split(" ")[0]);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDBControlStyle1 = new lib.jdb.control.jdbcontrolstyle.JDBControlStyle();
        jDBQueryLivro = new lib.jdb.jdbquery.JDBQuery();
        jDBQueryEmprestimos = new lib.jdb.jdbquery.JDBQuery();
        jDBTableStyle1 = new lib.jdb.control.jdbtable.JDBTableStyle();
        jDBQuerySlaveUsuario = new lib.jdb.jdbquery.JDBQuerySlave();
        jDBQuerySlaveEmpLivros = new lib.jdb.jdbquery.JDBQuerySlave();
        jScrollPane2 = new javax.swing.JScrollPane();
        jDBTable2 = new lib.jdb.control.jdbtable.JDBTable();
        jLabel5 = new javax.swing.JLabel();
        jDBTextFieldPzDev = new lib.jdb.control.jdbtextfield.JDBTextField();
        jDBTextFieldIdLivro = new lib.jdb.control.jdbtextfield.JDBTextField();
        jLabel7 = new javax.swing.JLabel();
        jButtonSelUsuario1 = new javax.swing.JButton();
        jDBTextField4 = new lib.jdb.control.jdbtextfield.JDBTextField();
        jLabel8 = new javax.swing.JLabel();
        jDBTextFieldDataDev = new lib.jdb.control.jdbtextfield.JDBTextField();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jDateChooserDataDev = new com.toedter.calendar.JDateChooser();
        jPanel1 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jDBTextField2 = new lib.jdb.control.jdbtextfield.JDBTextField();
        jDBTextField1 = new lib.jdb.control.jdbtextfield.JDBTextField();
        jDBTextField3 = new lib.jdb.control.jdbtextfield.JDBTextField();
        jDBTextField5 = new lib.jdb.control.jdbtextfield.JDBTextField();
        jDBTextFieldIdUser = new lib.jdb.control.jdbtextfield.JDBTextField();
        jPanel2 = new javax.swing.JPanel();
        jToolBar1 = new javax.swing.JToolBar();
        jDBButtonSave1 = new lib.jdb.control.jdbbuttonsave.JDBButtonSave();
        jDBButtonNew1 = new lib.jdb.control.jdbbuttonnew.JDBButtonNew();
        jDBButtonCancel1 = new lib.jdb.control.jdbbuttoncancel.JDBButtonCancel();
        jDBButtonDelete1 = new lib.jdb.control.jdbbuttondelete.JDBButtonDelete();
        jToolBar2 = new javax.swing.JToolBar();
        jDBButtonFirst1 = new lib.jdb.control.jdbbuttonfirst.JDBButtonFirst();
        jDBButtonPrevious1 = new lib.jdb.control.jdbbuttonprevious.JDBButtonPrevious();
        jLabelPosicao = new javax.swing.JLabel();
        jDBLabelCount1 = new lib.jdb.control.jdblabelcount.JDBLabelCount();
        jDBButtonNext1 = new lib.jdb.control.jdbbuttonnext.JDBButtonNext();
        jDBButtonLast1 = new lib.jdb.control.jdbbuttonlast.JDBButtonLast();
        jToolBar3 = new javax.swing.JToolBar();
        jButton1 = new javax.swing.JButton();

        jDBQueryEmprestimos.setSQL("select * from emprestimo");
        jDBQueryEmprestimos.addScrollEventListener(new lib.jdb.jdbquery.event.ScrollEventListener() {
            public void beforeScroll(lib.jdb.jdbquery.event.ScrollEventObject evt) {
            }
            public void afterScroll(lib.jdb.jdbquery.event.ScrollEventObject evt) {
                jDBQueryEmprestimosAfterScroll(evt);
            }
        });

        jDBQuerySlaveUsuario.setJDBQueryMaster(jDBQueryEmprestimos);
        jDBQuerySlaveUsuario.setSQL("select * from usuario where id = {$usuario_id}");
        jDBQuerySlaveUsuario.setMasterKeyField("usuario_id");
        jDBQuerySlaveUsuario.setSlaveForeignKeyField("id");

        jDBQuerySlaveEmpLivros.setJDBQueryMaster(jDBQueryEmprestimos);
        jDBQuerySlaveEmpLivros.setSQL("select * from emprestimo_livros where emprestimo_id = {$id}");
        jDBQuerySlaveEmpLivros.setMasterKeyField("id");
        jDBQuerySlaveEmpLivros.setSaveManually(true);
        jDBQuerySlaveEmpLivros.setSlaveForeignKeyField("emprestimo_id");
        jDBQuerySlaveEmpLivros.addInsertEventListener(new lib.jdb.jdbquery.event.InsertEventListener() {
            public void beforeInsert(lib.jdb.jdbquery.event.InsertEventObject evt) {
                jDBQuerySlaveEmpLivrosBeforeInsert(evt);
            }
            public void afterInsert(lib.jdb.jdbquery.event.InsertEventObject evt) {
            }
        });
        jDBQuerySlaveEmpLivros.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                jDBQuerySlaveEmpLivrosPropertyChange(evt);
            }
        });
        jDBQuerySlaveEmpLivros.addSaveEventListener(new lib.jdb.jdbquery.event.SaveEventListener() {
            public void beforeSave(lib.jdb.jdbquery.event.SaveEventObject evt) {
            }
            public void afterSave(lib.jdb.jdbquery.event.SaveEventObject evt) {
                jDBQuerySlaveEmpLivrosAfterSave(evt);
            }
        });
        jDBQuerySlaveEmpLivros.addSaveManuallyEventListener(new lib.jdb.jdbquery.event.SaveManuallyEventListener() {
            public void onSaveManually(lib.jdb.jdbquery.event.SaveManuallyEventObject evt) {
                jDBQuerySlaveEmpLivrosOnSaveManually(evt);
            }
        });
        jDBQuerySlaveEmpLivros.addScrollEventListener(new lib.jdb.jdbquery.event.ScrollEventListener() {
            public void beforeScroll(lib.jdb.jdbquery.event.ScrollEventObject evt) {
            }
            public void afterScroll(lib.jdb.jdbquery.event.ScrollEventObject evt) {
                jDBQuerySlaveEmpLivrosAfterScroll(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Livros do Empréstimo");

        jDBTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jDBTable2.setJDBQuery(jDBQuerySlaveEmpLivros);
        jDBTable2.setEditable(false);
        jDBTable2.setInvisibleFields("emprestimo_id");
        jDBTable2.setjDBTableStyle(jDBTableStyle1);
        jScrollPane2.setViewportView(jDBTable2);

        jLabel5.setText("Pz. Devolução");

        jDBTextFieldPzDev.setJDBQuery(jDBQuerySlaveEmpLivros);
        jDBTextFieldPzDev.setFieldName("prazo_devolucao");
        jDBTextFieldPzDev.setjDBControlStyle(jDBControlStyle1);

        jDBTextFieldIdLivro.setJDBQuery(jDBQuerySlaveEmpLivros);
        jDBTextFieldIdLivro.setFieldName("livro_id");
        jDBTextFieldIdLivro.setjDBControlStyle(jDBControlStyle1);
        jDBTextFieldIdLivro.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jDBTextFieldIdLivroKeyReleased(evt);
            }
        });

        jLabel7.setText("Tombo / Livro");

        jButtonSelUsuario1.setText("...");
        jButtonSelUsuario1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSelUsuario1ActionPerformed(evt);
            }
        });

        jDBTextField4.setEditable(false);
        jDBTextField4.setJDBQuery(jDBQueryLivro);
        jDBTextField4.setFieldName("livro");
        jDBTextField4.setjDBControlStyle(jDBControlStyle1);

        jLabel8.setText("Data Devolução");

        jDBTextFieldDataDev.setJDBQuery(jDBQuerySlaveEmpLivros);
        jDBTextFieldDataDev.setFieldName("data_devolucao");
        jDBTextFieldDataDev.setjDBControlStyle(jDBControlStyle1);

        jDateChooser1.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                jDateChooser1PropertyChange(evt);
            }
        });

        jDateChooserDataDev.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                jDateChooserDataDevPropertyChange(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Empréstimo"));

        jLabel6.setText("Código / Data");

        jLabel2.setText("RG");

        jLabel4.setText("Código / Usuário");

        jDBTextField2.setEditable(false);
        jDBTextField2.setJDBQuery(jDBQuerySlaveUsuario);
        jDBTextField2.setFieldName("rg");
        jDBTextField2.setjDBControlStyle(jDBControlStyle1);

        jDBTextField1.setEditable(false);
        jDBTextField1.setJDBQuery(jDBQuerySlaveUsuario);
        jDBTextField1.setFieldName("nome");
        jDBTextField1.setjDBControlStyle(jDBControlStyle1);

        jDBTextField3.setEditable(false);
        jDBTextField3.setJDBQuery(jDBQueryEmprestimos);
        jDBTextField3.setFieldName("data");
        jDBTextField3.setjDBControlStyle(jDBControlStyle1);

        jDBTextField5.setEditable(false);
        jDBTextField5.setJDBQuery(jDBQueryEmprestimos);
        jDBTextField5.setFieldName("id");
        jDBTextField5.setjDBControlStyle(jDBControlStyle1);

        jDBTextFieldIdUser.setEditable(false);
        jDBTextFieldIdUser.setJDBQuery(jDBQueryEmprestimos);
        jDBTextFieldIdUser.setFieldName("usuario_id");
        jDBTextFieldIdUser.setjDBControlStyle(jDBControlStyle1);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jDBTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jDBTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel6))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jDBTextFieldIdUser, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jDBTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jDBTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel4)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jDBTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jDBTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jDBTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jDBTextFieldIdUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jDBTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jToolBar1.setRollover(true);

        jDBButtonSave1.setJDBQuery(jDBQuerySlaveEmpLivros);
        jDBButtonSave1.setFocusable(false);
        jDBButtonSave1.setHorizontalTextPosition(0);
        jDBButtonSave1.setText("");
        jDBButtonSave1.setToolTipText("Salvar");
        jDBButtonSave1.setVerticalTextPosition(3);
        jToolBar1.add(jDBButtonSave1);

        jDBButtonNew1.setJDBQuery(jDBQuerySlaveEmpLivros);
        jDBButtonNew1.setFocusable(false);
        jDBButtonNew1.setHorizontalTextPosition(0);
        jDBButtonNew1.setText("");
        jDBButtonNew1.setToolTipText("Novo");
        jDBButtonNew1.setVerticalTextPosition(3);
        jDBButtonNew1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jDBButtonNew1ActionPerformed(evt);
            }
        });
        jToolBar1.add(jDBButtonNew1);

        jDBButtonCancel1.setJDBQuery(jDBQuerySlaveEmpLivros);
        jDBButtonCancel1.setFocusable(false);
        jDBButtonCancel1.setHorizontalTextPosition(0);
        jDBButtonCancel1.setText("");
        jDBButtonCancel1.setToolTipText("Cancelar");
        jDBButtonCancel1.setVerticalTextPosition(3);
        jDBButtonCancel1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jDBButtonCancel1ActionPerformed(evt);
            }
        });
        jToolBar1.add(jDBButtonCancel1);

        jDBButtonDelete1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/del.png"))); // NOI18N
        jDBButtonDelete1.setJDBQuery(jDBQuerySlaveEmpLivros);
        jDBButtonDelete1.setFocusable(false);
        jDBButtonDelete1.setHorizontalTextPosition(0);
        jDBButtonDelete1.setText("");
        jDBButtonDelete1.setToolTipText("Excluir");
        jDBButtonDelete1.setVerticalTextPosition(3);
        jToolBar1.add(jDBButtonDelete1);

        jToolBar2.setRollover(true);

        jDBButtonFirst1.setJDBQuery(jDBQuerySlaveEmpLivros);
        jDBButtonFirst1.setFocusable(false);
        jDBButtonFirst1.setHorizontalTextPosition(0);
        jDBButtonFirst1.setText("");
        jDBButtonFirst1.setVerticalTextPosition(3);
        jToolBar2.add(jDBButtonFirst1);

        jDBButtonPrevious1.setJDBQuery(jDBQuerySlaveEmpLivros);
        jDBButtonPrevious1.setFocusable(false);
        jDBButtonPrevious1.setHorizontalTextPosition(0);
        jDBButtonPrevious1.setText("");
        jDBButtonPrevious1.setVerticalTextPosition(3);
        jToolBar2.add(jDBButtonPrevious1);

        jLabelPosicao.setText("0 / ");
        jToolBar2.add(jLabelPosicao);

        jDBLabelCount1.setjDBQuery(jDBQuerySlaveEmpLivros);
        jToolBar2.add(jDBLabelCount1);

        jDBButtonNext1.setJDBQuery(jDBQuerySlaveEmpLivros);
        jDBButtonNext1.setFocusable(false);
        jDBButtonNext1.setHorizontalTextPosition(0);
        jDBButtonNext1.setText("");
        jDBButtonNext1.setVerticalTextPosition(3);
        jToolBar2.add(jDBButtonNext1);

        jDBButtonLast1.setJDBQuery(jDBQuerySlaveEmpLivros);
        jDBButtonLast1.setFocusable(false);
        jDBButtonLast1.setHorizontalTextPosition(0);
        jDBButtonLast1.setText("");
        jDBButtonLast1.setVerticalTextPosition(3);
        jToolBar2.add(jDBButtonLast1);

        jToolBar3.setRollover(true);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cancel.png"))); // NOI18N
        jButton1.setToolTipText("Fechar");
        jButton1.setFocusable(false);
        jButton1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jToolBar3.add(jButton1);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jToolBar2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jToolBar3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jToolBar3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jToolBar2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(13, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jDBTextFieldPzDev, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jDBTextFieldDataDev, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jDateChooserDataDev, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButtonSelUsuario1))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jDBTextFieldIdLivro, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jDBTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 294, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(30, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jScrollPane2)
                            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 0, Short.MAX_VALUE))))
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jDBTextFieldPzDev, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jDBTextFieldIdLivro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jDBTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jDBTextFieldDataDev, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButtonSelUsuario1)
                            .addComponent(jLabel7))
                        .addGap(33, 33, 33))
                    .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jDateChooserDataDev, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 98, Short.MAX_VALUE)
                .addGap(49, 49, 49))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jDBButtonNew1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jDBButtonNew1ActionPerformed
        jDBTextFieldIdLivro.requestFocus();
    }//GEN-LAST:event_jDBButtonNew1ActionPerformed

    private void jDBQueryEmprestimosAfterScroll(lib.jdb.jdbquery.event.ScrollEventObject evt) {//GEN-FIRST:event_jDBQueryEmprestimosAfterScroll
        
    }//GEN-LAST:event_jDBQueryEmprestimosAfterScroll

    private void jDBQuerySlaveEmpLivrosAfterScroll(lib.jdb.jdbquery.event.ScrollEventObject evt) {//GEN-FIRST:event_jDBQuerySlaveEmpLivrosAfterScroll
        jDBQueryLivro.setSQL(qryLivro+" where l.id = "+jDBQuerySlaveEmpLivros.getCurrentFieldValue("livro_id"));
                    jDBQueryLivro.execQuery();
                    jLabelPosicao.setText(Integer.toString(jDBQuerySlaveEmpLivros.getRow())+" / ");
    }//GEN-LAST:event_jDBQuerySlaveEmpLivrosAfterScroll

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jDBButtonCancel1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jDBButtonCancel1ActionPerformed
        jDBQueryLivro.setSQL(qryLivro+ " where l.id = "+jDBQuerySlaveEmpLivros.getCurrentFieldValue("livro_id"));
                    jDBQueryLivro.execQuery();
    }//GEN-LAST:event_jDBButtonCancel1ActionPerformed

    private void jDateChooser1PropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jDateChooser1PropertyChange
        if(evt.getPropertyName().equals("date")){
            jDBTextFieldPzDev.setText(jDateChooser1.getJCalendar().getDate().toLocaleString().split(" ")[0]);
            jDBQuerySlaveEmpLivros.edit();
            jDBQuerySlaveEmpLivros.setNewCurrentFieldValue("prazo_devolucao", jDBTextFieldPzDev.getText());
        }
    }//GEN-LAST:event_jDateChooser1PropertyChange

    private void jDateChooserDataDevPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jDateChooserDataDevPropertyChange
        if(evt.getPropertyName().equals("date")){
            jDBTextFieldDataDev.setText(jDateChooserDataDev.getJCalendar().getDate().toLocaleString().split(" ")[0]);
            jDBQuerySlaveEmpLivros.edit();
            jDBQuerySlaveEmpLivros.setNewCurrentFieldValue("data_devolucao", jDBTextFieldDataDev.getText());
            
        }
    }//GEN-LAST:event_jDateChooserDataDevPropertyChange

    private void jDBTextFieldIdLivroKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jDBTextFieldIdLivroKeyReleased
        if(evt.getKeyCode()==KeyEvent.VK_ENTER){
            jDBQuerySlaveEmpLivros.insert();
        }else{
            if(jDBTextFieldIdLivro.getText().matches("\\d+")){
                jDBQueryLivro.setSQL(qryLivro+" where l.id ="+jDBTextFieldIdLivro.getText());
                jDBQueryLivro.execQuery();
            }else{
                jDBQueryLivro.setSQL(qryLivro+" where l.id =0");
                jDBQueryLivro.execQuery();
            }
        }
    }//GEN-LAST:event_jDBTextFieldIdLivroKeyReleased

    private void jButtonSelUsuario1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSelUsuario1ActionPerformed
        JFLivros jfl = new JFLivros(jDBQueryEmprestimos.getJDBConnection(), true);
        jfl.show();
        jfl.addWindowListener(new WindowListener() {
            @Override public void windowOpened(WindowEvent e) {}
            @Override public void windowClosing(WindowEvent e) {}
            @Override public void windowClosed(WindowEvent e) {
                if(jfl.selecionar){
                    if(jfl.isDisponivel()){
                        jDBQueryLivro.setSQL(qryLivro+ " where l.id = "+jfl.getId());
                        jDBQueryLivro.execQuery();
                        jDBTextFieldIdLivro.setText(jfl.getId());
                        jDBQuerySlaveEmpLivros.edit();
                        jDBQuerySlaveEmpLivros.setNewCurrentFieldValue("livro_id", jfl.getId());
                    }else
                    JOptionPane.showMessageDialog(null, "Livro indisponível");
                }
            }
            @Override public void windowIconified(WindowEvent e) {}
            @Override public void windowDeiconified(WindowEvent e) {}
            @Override public void windowActivated(WindowEvent e) {}
            @Override public void windowDeactivated(WindowEvent e) {}
        });
    }//GEN-LAST:event_jButtonSelUsuario1ActionPerformed

    private void jDBQuerySlaveEmpLivrosOnSaveManually(lib.jdb.jdbquery.event.SaveManuallyEventObject evt) {//GEN-FIRST:event_jDBQuerySlaveEmpLivrosOnSaveManually
        jDBQuerySlaveEmpLivros.setNewCurrentFieldValue("prazo_devolucao", 
                jDBTextFieldPzDev.getText());
            
        jDBQuerySlaveEmpLivros.save();
    }//GEN-LAST:event_jDBQuerySlaveEmpLivrosOnSaveManually

    private void jDBQuerySlaveEmpLivrosAfterSave(lib.jdb.jdbquery.event.SaveEventObject evt) {//GEN-FIRST:event_jDBQuerySlaveEmpLivrosAfterSave
        jDBQuerySlaveEmpLivros.insert();
        jDBTextFieldIdLivro.requestFocus();
    }//GEN-LAST:event_jDBQuerySlaveEmpLivrosAfterSave

    private void jDBQuerySlaveEmpLivrosBeforeInsert(lib.jdb.jdbquery.event.InsertEventObject evt) {//GEN-FIRST:event_jDBQuerySlaveEmpLivrosBeforeInsert
        setPzDevDefault();
    }//GEN-LAST:event_jDBQuerySlaveEmpLivrosBeforeInsert

    private void jDBQuerySlaveEmpLivrosPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jDBQuerySlaveEmpLivrosPropertyChange
        jDBButtonDelete1.setEnabled(!jDBQuerySlaveEmpLivros.isInserting()&&!jDBQuerySlaveEmpLivros.isEditing());
        jDBButtonNew1.setEnabled(!jDBQuerySlaveEmpLivros.isInserting()&&!jDBQuerySlaveEmpLivros.isEditing());
        jDBButtonNext1.setEnabled(!jDBQuerySlaveEmpLivros.isInserting()&&!jDBQuerySlaveEmpLivros.isEditing()&&
                jDBQuerySlaveEmpLivros.getRow()<jDBQuerySlaveEmpLivros.getQueryQuantity());
        jDBButtonLast1.setEnabled(!jDBQuerySlaveEmpLivros.isInserting()&&
                                !jDBQuerySlaveEmpLivros.isEditing()&&
                jDBQuerySlaveEmpLivros.getRow()<jDBQuerySlaveEmpLivros.getQueryQuantity());
        jDBButtonPrevious1.setEnabled(!jDBQuerySlaveEmpLivros.isInserting()&&!jDBQuerySlaveEmpLivros.isEditing()&&
                jDBQuerySlaveEmpLivros.getRow()>1);
        jDBButtonFirst1.setEnabled(!jDBQuerySlaveEmpLivros.isInserting()&&!jDBQuerySlaveEmpLivros.isEditing()&&
                jDBQuerySlaveEmpLivros.getRow()>1);
        jDBButtonSave1.setEnabled(jDBQuerySlaveEmpLivros.isEditing() || jDBQuerySlaveEmpLivros.isInserting());
        jDBButtonCancel1.setEnabled(jDBQuerySlaveEmpLivros.isEditing() || jDBQuerySlaveEmpLivros.isInserting());
    }//GEN-LAST:event_jDBQuerySlaveEmpLivrosPropertyChange

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFEmprestimoLivros().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButtonSelUsuario1;
    private lib.jdb.control.jdbbuttoncancel.JDBButtonCancel jDBButtonCancel1;
    private lib.jdb.control.jdbbuttondelete.JDBButtonDelete jDBButtonDelete1;
    private lib.jdb.control.jdbbuttonfirst.JDBButtonFirst jDBButtonFirst1;
    private lib.jdb.control.jdbbuttonlast.JDBButtonLast jDBButtonLast1;
    private lib.jdb.control.jdbbuttonnew.JDBButtonNew jDBButtonNew1;
    private lib.jdb.control.jdbbuttonnext.JDBButtonNext jDBButtonNext1;
    private lib.jdb.control.jdbbuttonprevious.JDBButtonPrevious jDBButtonPrevious1;
    private lib.jdb.control.jdbbuttonsave.JDBButtonSave jDBButtonSave1;
    private lib.jdb.control.jdbcontrolstyle.JDBControlStyle jDBControlStyle1;
    private lib.jdb.control.jdblabelcount.JDBLabelCount jDBLabelCount1;
    private lib.jdb.jdbquery.JDBQuery jDBQueryEmprestimos;
    private lib.jdb.jdbquery.JDBQuery jDBQueryLivro;
    private lib.jdb.jdbquery.JDBQuerySlave jDBQuerySlaveEmpLivros;
    private lib.jdb.jdbquery.JDBQuerySlave jDBQuerySlaveUsuario;
    private lib.jdb.control.jdbtable.JDBTable jDBTable2;
    private lib.jdb.control.jdbtable.JDBTableStyle jDBTableStyle1;
    private lib.jdb.control.jdbtextfield.JDBTextField jDBTextField1;
    private lib.jdb.control.jdbtextfield.JDBTextField jDBTextField2;
    private lib.jdb.control.jdbtextfield.JDBTextField jDBTextField3;
    private lib.jdb.control.jdbtextfield.JDBTextField jDBTextField4;
    private lib.jdb.control.jdbtextfield.JDBTextField jDBTextField5;
    private lib.jdb.control.jdbtextfield.JDBTextField jDBTextFieldDataDev;
    private lib.jdb.control.jdbtextfield.JDBTextField jDBTextFieldIdLivro;
    private lib.jdb.control.jdbtextfield.JDBTextField jDBTextFieldIdUser;
    private lib.jdb.control.jdbtextfield.JDBTextField jDBTextFieldPzDev;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private com.toedter.calendar.JDateChooser jDateChooserDataDev;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabelPosicao;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JToolBar jToolBar2;
    private javax.swing.JToolBar jToolBar3;
    // End of variables declaration//GEN-END:variables
}
