
import java.awt.event.WindowEvent;
import java.awt.event.WindowListener;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import lib.jdb.connection.JDBConnection;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author vmf
 */
public class JFEmprestimoLivros extends javax.swing.JFrame {
    String qryLivro ="select concat(t.titulo, \" | \",au.autor,\" | \",a.assunto) as \"livro\" from livro l inner join"
                            + " titulo t on t.id = l.titulo_id inner join assunto a on a.id = t.assunto_id "
                                + " inner join autor au on t.autor_id = au.id ";
    /**
     * Creates new form JFAluno
     */
    public JFEmprestimoLivros() {
        initComponents();
        jDBTable2.setFieldsTitle("id", "Código");
        jDBTable2.setFieldsTitle("livro_id", "Tombo");
        jDBTable2.setFieldsTitle("emprestimo_id", "Cód. Empréstimo");
        jDBTable2.setFieldsTitle("data_devolucao", "Data da Devolução");
        jDBTable2.setFieldsTitle("prazo_devolucao", "Prazo de Devolução");
    }
    public JFEmprestimoLivros(JDBConnection jdb, String emp_id) {
        this();
        jDBQuerySlaveUsuario.setJDBConnection(jdb);
        jDBQuerySlaveEmpLivros.setJDBConnection(jdb);
        jDBQueryEmprestimos.setJDBConnection(jdb);
        jDBQueryLivro.setJDBConnection(jdb);
        jDBQueryEmprestimos.setSQL("select * from emprestimo where id = "+emp_id);
        jDBQueryEmprestimos.execQuery();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDBControlStyle1 = new lib.jdb.control.jdbcontrolstyle.JDBControlStyle();
        jDBQueryLivro = new lib.jdb.jdbquery.JDBQuery();
        jDBQueryEmprestimos = new lib.jdb.jdbquery.JDBQuery();
        jDBTableStyle1 = new lib.jdb.control.jdbtable.JDBTableStyle();
        jDBQuerySlaveUsuario = new lib.jdb.jdbquery.JDBQuerySlave();
        jDBQuerySlaveEmpLivros = new lib.jdb.jdbquery.JDBQuerySlave();
        jDBButtonNew1 = new lib.jdb.control.jdbbuttonnew.JDBButtonNew();
        jDBButtonSave1 = new lib.jdb.control.jdbbuttonsave.JDBButtonSave();
        jDBButtonCancel1 = new lib.jdb.control.jdbbuttoncancel.JDBButtonCancel();
        jDBTextField1 = new lib.jdb.control.jdbtextfield.JDBTextField();
        jLabel1 = new javax.swing.JLabel();
        jDBTextField2 = new lib.jdb.control.jdbtextfield.JDBTextField();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jDBTable2 = new lib.jdb.control.jdbtable.JDBTable();
        jLabel3 = new javax.swing.JLabel();
        jDBTextField3 = new lib.jdb.control.jdbtextfield.JDBTextField();
        jDBTextFieldIdUser = new lib.jdb.control.jdbtextfield.JDBTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jDBTextFieldPzDev = new lib.jdb.control.jdbtextfield.JDBTextField();
        jDBTextFieldIdLivro = new lib.jdb.control.jdbtextfield.JDBTextField();
        jLabel7 = new javax.swing.JLabel();
        jButtonSelUsuario1 = new javax.swing.JButton();
        jDBTextField4 = new lib.jdb.control.jdbtextfield.JDBTextField();
        jDBButtonDelete1 = new lib.jdb.control.jdbbuttondelete.JDBButtonDelete();
        jLabel8 = new javax.swing.JLabel();
        jDBTextFieldDataDev = new lib.jdb.control.jdbtextfield.JDBTextField();
        jSeparator2 = new javax.swing.JSeparator();
        jDBButtonFirst1 = new lib.jdb.control.jdbbuttonfirst.JDBButtonFirst();
        jDBButtonPrevious1 = new lib.jdb.control.jdbbuttonprevious.JDBButtonPrevious();
        jDBButtonNext1 = new lib.jdb.control.jdbbuttonnext.JDBButtonNext();
        jDBButtonLast1 = new lib.jdb.control.jdbbuttonlast.JDBButtonLast();
        jSeparator3 = new javax.swing.JSeparator();
        jButton1 = new javax.swing.JButton();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jDateChooserDataDev = new com.toedter.calendar.JDateChooser();

        jDBQueryEmprestimos.setSQL("select * from emprestimo");
        jDBQueryEmprestimos.addScrollEventListener(new lib.jdb.jdbquery.event.ScrollEventListener() {
            public void beforeScroll(lib.jdb.jdbquery.event.ScrollEventObject evt) {
            }
            public void afterScroll(lib.jdb.jdbquery.event.ScrollEventObject evt) {
                jDBQueryEmprestimosAfterScroll(evt);
            }
        });

        jDBQuerySlaveUsuario.setJDBQueryMaster(jDBQueryEmprestimos);
        jDBQuerySlaveUsuario.setSQL("select * from usuario where id = {$usuario_id}");
        jDBQuerySlaveUsuario.setMasterKeyField("usuario_id");
        jDBQuerySlaveUsuario.setSlaveForeignKeyField("id");

        jDBQuerySlaveEmpLivros.setJDBQueryMaster(jDBQueryEmprestimos);
        jDBQuerySlaveEmpLivros.setSQL("select * from emprestimo_livros where emprestimo_id = {$id}");
        jDBQuerySlaveEmpLivros.setMasterKeyField("id");
        jDBQuerySlaveEmpLivros.setSlaveForeignKeyField("emprestimo_id");
        jDBQuerySlaveEmpLivros.addScrollEventListener(new lib.jdb.jdbquery.event.ScrollEventListener() {
            public void beforeScroll(lib.jdb.jdbquery.event.ScrollEventObject evt) {
            }
            public void afterScroll(lib.jdb.jdbquery.event.ScrollEventObject evt) {
                jDBQuerySlaveEmpLivrosAfterScroll(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Livros do Empréstimo");

        jDBButtonNew1.setJDBQuery(jDBQuerySlaveEmpLivros);
        jDBButtonNew1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jDBButtonNew1ActionPerformed(evt);
            }
        });

        jDBButtonSave1.setJDBQuery(jDBQuerySlaveEmpLivros);

        jDBButtonCancel1.setJDBQuery(jDBQuerySlaveEmpLivros);
        jDBButtonCancel1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jDBButtonCancel1ActionPerformed(evt);
            }
        });

        jDBTextField1.setEditable(false);
        jDBTextField1.setJDBQuery(jDBQuerySlaveUsuario);
        jDBTextField1.setFieldName("nome");
        jDBTextField1.setjDBControlStyle(jDBControlStyle1);

        jLabel1.setText("Nome do Usuário");

        jDBTextField2.setEditable(false);
        jDBTextField2.setJDBQuery(jDBQuerySlaveUsuario);
        jDBTextField2.setFieldName("rg");
        jDBTextField2.setjDBControlStyle(jDBControlStyle1);

        jLabel2.setText("RG");

        jDBTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jDBTable2.setJDBQuery(jDBQuerySlaveEmpLivros);
        jDBTable2.setEditable(false);
        jDBTable2.setjDBTableStyle(jDBTableStyle1);
        jScrollPane2.setViewportView(jDBTable2);

        jLabel3.setText("Data");

        jDBTextField3.setEditable(false);
        jDBTextField3.setJDBQuery(jDBQueryEmprestimos);
        jDBTextField3.setFieldName("data");
        jDBTextField3.setjDBControlStyle(jDBControlStyle1);

        jDBTextFieldIdUser.setEditable(false);
        jDBTextFieldIdUser.setJDBQuery(jDBQueryEmprestimos);
        jDBTextFieldIdUser.setFieldName("usuario_id");
        jDBTextFieldIdUser.setjDBControlStyle(jDBControlStyle1);

        jLabel4.setText("Cod. Usuário");

        jLabel5.setText("Pz. Devolução");

        jDBTextFieldPzDev.setJDBQuery(jDBQuerySlaveEmpLivros);
        jDBTextFieldPzDev.setFieldName("prazo_devolucao");
        jDBTextFieldPzDev.setjDBControlStyle(jDBControlStyle1);

        jDBTextFieldIdLivro.setJDBQuery(jDBQuerySlaveEmpLivros);
        jDBTextFieldIdLivro.setFieldName("livro_id");
        jDBTextFieldIdLivro.setjDBControlStyle(jDBControlStyle1);
        jDBTextFieldIdLivro.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jDBTextFieldIdLivroKeyReleased(evt);
            }
        });

        jLabel7.setText("Tombo / Livro");

        jButtonSelUsuario1.setText("...");
        jButtonSelUsuario1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSelUsuario1ActionPerformed(evt);
            }
        });

        jDBTextField4.setEditable(false);
        jDBTextField4.setJDBQuery(jDBQueryLivro);
        jDBTextField4.setFieldName("livro");
        jDBTextField4.setjDBControlStyle(jDBControlStyle1);

        jDBButtonDelete1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones.png"))); // NOI18N
        jDBButtonDelete1.setJDBQuery(jDBQuerySlaveEmpLivros);

        jLabel8.setText("Data Devolução");

        jDBTextFieldDataDev.setJDBQuery(jDBQuerySlaveEmpLivros);
        jDBTextFieldDataDev.setFieldName("data_devolucao");
        jDBTextFieldDataDev.setjDBControlStyle(jDBControlStyle1);

        jDBButtonFirst1.setJDBQuery(jDBQuerySlaveEmpLivros);

        jDBButtonPrevious1.setJDBQuery(jDBQuerySlaveEmpLivros);

        jDBButtonNext1.setJDBQuery(jDBQuerySlaveEmpLivros);

        jDBButtonLast1.setJDBQuery(jDBQuerySlaveEmpLivros);

        jSeparator3.setOrientation(javax.swing.SwingConstants.VERTICAL);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/quit.png"))); // NOI18N
        jButton1.setText("Fechar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jDateChooser1.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                jDateChooser1PropertyChange(evt);
            }
        });

        jDateChooserDataDev.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                jDateChooserDataDevPropertyChange(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator2)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jDBTextFieldPzDev, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jDBTextFieldDataDev, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jDateChooserDataDev, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButtonSelUsuario1)
                                .addGap(285, 285, 285))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jDBTextFieldIdLivro, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jDBTextField4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(64, 64, 64))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jDBTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jDBTextFieldIdUser, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel4))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(jDBTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jDBTextField2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jDBButtonFirst1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jDBButtonPrevious1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jDBButtonNext1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jDBButtonLast1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jDBButtonNew1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jDBButtonSave1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jDBButtonDelete1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jDBButtonCancel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(186, 186, 186))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jDBTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jDBTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jDBTextFieldIdUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jDBTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jDBButtonDelete1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jDBButtonCancel1, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jDBButtonSave1, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jDBButtonNew1, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jDBButtonFirst1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jDBButtonPrevious1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jDBButtonNext1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jDBButtonLast1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addComponent(jSeparator3))
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jDBTextFieldPzDev, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jDBTextFieldIdLivro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jDBTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jDBTextFieldDataDev, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButtonSelUsuario1)
                            .addComponent(jLabel7))
                        .addGap(33, 33, 33))
                    .addComponent(jDateChooserDataDev, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 228, Short.MAX_VALUE)
                .addGap(49, 49, 49))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jDBButtonNew1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jDBButtonNew1ActionPerformed
    
    }//GEN-LAST:event_jDBButtonNew1ActionPerformed

    private void jDBQueryEmprestimosAfterScroll(lib.jdb.jdbquery.event.ScrollEventObject evt) {//GEN-FIRST:event_jDBQueryEmprestimosAfterScroll
        
    }//GEN-LAST:event_jDBQueryEmprestimosAfterScroll

    private void jDBQuerySlaveEmpLivrosAfterScroll(lib.jdb.jdbquery.event.ScrollEventObject evt) {//GEN-FIRST:event_jDBQuerySlaveEmpLivrosAfterScroll
        jDBQueryLivro.setSQL(qryLivro+" where l.id = "+jDBQuerySlaveEmpLivros.getCurrentFieldValue("livro_id"));
                    jDBQueryLivro.execQuery();
    }//GEN-LAST:event_jDBQuerySlaveEmpLivrosAfterScroll

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jDBButtonCancel1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jDBButtonCancel1ActionPerformed
        jDBQueryLivro.setSQL(qryLivro+ " where l.id = "+jDBQuerySlaveEmpLivros.getCurrentFieldValue("livro_id"));
                    jDBQueryLivro.execQuery();
    }//GEN-LAST:event_jDBButtonCancel1ActionPerformed

    private void jDateChooser1PropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jDateChooser1PropertyChange
        if(evt.getPropertyName().equals("date")){
            jDBTextFieldPzDev.setText(jDateChooser1.getJCalendar().getDate().toLocaleString().split(" ")[0]);
            jDBQuerySlaveEmpLivros.edit();
            jDBQuerySlaveEmpLivros.setNewCurrentFieldValue("prazo_devolucao", jDBTextFieldPzDev.getText());
        }
    }//GEN-LAST:event_jDateChooser1PropertyChange

    private void jDateChooserDataDevPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jDateChooserDataDevPropertyChange
        if(evt.getPropertyName().equals("date")){
            jDBTextFieldDataDev.setText(jDateChooserDataDev.getJCalendar().getDate().toLocaleString().split(" ")[0]);
            jDBQuerySlaveEmpLivros.edit();
            jDBQuerySlaveEmpLivros.setNewCurrentFieldValue("data_devolucao", jDBTextFieldDataDev.getText());
        }
    }//GEN-LAST:event_jDateChooserDataDevPropertyChange

    private void jDBTextFieldIdLivroKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jDBTextFieldIdLivroKeyReleased
        if(jDBTextFieldIdLivro.getText().matches("\\d")){
            jDBQueryLivro.setSQL(qryLivro+" where l.id ="+jDBTextFieldIdLivro.getText());
            jDBQueryLivro.execQuery();
        }
    }//GEN-LAST:event_jDBTextFieldIdLivroKeyReleased

    private void jButtonSelUsuario1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSelUsuario1ActionPerformed
        JFLivros jfl = new JFLivros(jDBQueryEmprestimos.getJDBConnection(), true);
        jfl.show();
        jfl.addWindowListener(new WindowListener() {
            @Override public void windowOpened(WindowEvent e) {}
            @Override public void windowClosing(WindowEvent e) {}
            @Override public void windowClosed(WindowEvent e) {
                if(jfl.selecionar){
                    if(jfl.isDisponivel()){
                        jDBQueryLivro.setSQL(qryLivro+ " where l.id = "+jfl.getId());
                        jDBQueryLivro.execQuery();
                        jDBTextFieldIdLivro.setText(jfl.getId());
                        jDBQuerySlaveEmpLivros.edit();
                        jDBQuerySlaveEmpLivros.setNewCurrentFieldValue("livro_id", jfl.getId());
                    }else
                    JOptionPane.showMessageDialog(null, "Livro indisponível");
                }
            }
            @Override public void windowIconified(WindowEvent e) {}
            @Override public void windowDeiconified(WindowEvent e) {}
            @Override public void windowActivated(WindowEvent e) {}
            @Override public void windowDeactivated(WindowEvent e) {}
        });
    }//GEN-LAST:event_jButtonSelUsuario1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFEmprestimoLivros().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButtonSelUsuario1;
    private lib.jdb.control.jdbbuttoncancel.JDBButtonCancel jDBButtonCancel1;
    private lib.jdb.control.jdbbuttondelete.JDBButtonDelete jDBButtonDelete1;
    private lib.jdb.control.jdbbuttonfirst.JDBButtonFirst jDBButtonFirst1;
    private lib.jdb.control.jdbbuttonlast.JDBButtonLast jDBButtonLast1;
    private lib.jdb.control.jdbbuttonnew.JDBButtonNew jDBButtonNew1;
    private lib.jdb.control.jdbbuttonnext.JDBButtonNext jDBButtonNext1;
    private lib.jdb.control.jdbbuttonprevious.JDBButtonPrevious jDBButtonPrevious1;
    private lib.jdb.control.jdbbuttonsave.JDBButtonSave jDBButtonSave1;
    private lib.jdb.control.jdbcontrolstyle.JDBControlStyle jDBControlStyle1;
    private lib.jdb.jdbquery.JDBQuery jDBQueryEmprestimos;
    private lib.jdb.jdbquery.JDBQuery jDBQueryLivro;
    private lib.jdb.jdbquery.JDBQuerySlave jDBQuerySlaveEmpLivros;
    private lib.jdb.jdbquery.JDBQuerySlave jDBQuerySlaveUsuario;
    private lib.jdb.control.jdbtable.JDBTable jDBTable2;
    private lib.jdb.control.jdbtable.JDBTableStyle jDBTableStyle1;
    private lib.jdb.control.jdbtextfield.JDBTextField jDBTextField1;
    private lib.jdb.control.jdbtextfield.JDBTextField jDBTextField2;
    private lib.jdb.control.jdbtextfield.JDBTextField jDBTextField3;
    private lib.jdb.control.jdbtextfield.JDBTextField jDBTextField4;
    private lib.jdb.control.jdbtextfield.JDBTextField jDBTextFieldDataDev;
    private lib.jdb.control.jdbtextfield.JDBTextField jDBTextFieldIdLivro;
    private lib.jdb.control.jdbtextfield.JDBTextField jDBTextFieldIdUser;
    private lib.jdb.control.jdbtextfield.JDBTextField jDBTextFieldPzDev;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private com.toedter.calendar.JDateChooser jDateChooserDataDev;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    // End of variables declaration//GEN-END:variables
}
