
import java.awt.event.WindowEvent;
import java.awt.event.WindowListener;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import lib.jdb.connection.JDBConnection;
import net.sf.jasperreports.engine.JRResultSetDataSource;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.view.JasperViewer;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author vmf
 */
public class JFLivros extends javax.swing.JFrame {
    public boolean selecionar = false;
    public String qryLivros = "select * from livro where 1=1 ", 
            qryTitulo_ = "select t.id, t.titulo, a.assunto, t.resenha from titulo t inner join assunto a on t.assunto_id = a.id ",
            qryPrateleira = "select id, prateleira from prateleira ",
            qryTitulo = "select concat(t.titulo,\" | \",au.autor,\" | \",a.assunto) as titulo, a.categoriaprateleira_id from titulo t "
                            + "inner join assunto a on t.assunto_id = a.id "
                            + " inner join autor au on au.id = t.autor_id ",
            qryEditora = "select * from editora ",
            qryPrograma = "select * from programa";
    JFAssistenteCodBarras ja=null;
    /**
     * Creates new form JFAluno
     */
    public JFLivros() {
        initComponents();
        CustomTable.setDefaulttable(jDBTable1);
        jDBTable1.setFieldsTitle("edicao", "Edição");
        jDBTable1.setFieldsTitle("isbn", "ISBN");
        jDBTable1.setFieldsTitle("data_aquisicao", "Data Aquisição");
        jDBTable1.setFieldsTitle("id", "Tombo");
        jButtonevolver.setEnabled(false);
    }
    public JFLivros(JDBConnection jdb) {
        this();
        jDBQueryLivros.setJDBConnection(jdb);
        jDBQueryEditora.setJDBConnection(jdb);
        jDBQueryTitulo.setJDBConnection(jdb);
        jDBQueryPrograma.setJDBConnection(jdb);
        jDBQueryPrateleira.setJDBConnection(jdb);
        jDBQueryPrograma.execQuery();
        jDBQueryEditora.execQuery();
        jDBQueryLivros.execQuery();
        jDBQueryTitulo.execQuery();
        jButtonSelecionar.setEnabled(false);
        jDBUpdateTransaction1.setJDBConnection(jdb);
    }
    
    public JFLivros(JDBConnection jdb, boolean selecionar) {
        this();
        jDBQueryLivros.setJDBConnection(jdb);
        jDBQueryEditora.setJDBConnection(jdb);
        jDBQueryTitulo.setJDBConnection(jdb);
        jDBQueryPrograma.setJDBConnection(jdb);
        jDBQueryPrateleira.setJDBConnection(jdb);
        jDBQueryPrograma.execQuery();
        jDBQueryEditora.execQuery();
        jDBQueryTitulo.execQuery();
        jDBQueryLivros.setSQL(qryLivros+" and id = 0");
        jDBQueryLivros.execQuery();
        jDBUpdateTransaction1.setJDBConnection(jdb);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDBQueryLivros = new lib.jdb.jdbquery.JDBQuery();
        jDBControlStyle1 = new lib.jdb.control.jdbcontrolstyle.JDBControlStyle();
        jDBQueryTitulo = new lib.jdb.jdbquery.JDBQuery();
        jDBQueryEditora = new lib.jdb.jdbquery.JDBQuery();
        jDBQueryPrograma = new lib.jdb.jdbquery.JDBQuery();
        jDBTableStyle1 = new lib.jdb.control.jdbtable.JDBTableStyle();
        jDBQueryPrateleira = new lib.jdb.jdbquery.JDBQuery();
        jDBUpdateTransaction1 = new lib.jdb.jdbupdatetransaction.JDBUpdateTransaction();
        jDBButtonNew1 = new lib.jdb.control.jdbbuttonnew.JDBButtonNew();
        jDBButtonSave1 = new lib.jdb.control.jdbbuttonsave.JDBButtonSave();
        jDBButtonCancel1 = new lib.jdb.control.jdbbuttoncancel.JDBButtonCancel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jDBTable1 = new lib.jdb.control.jdbtable.JDBTable();
        jDBTextField3 = new lib.jdb.control.jdbtextfield.JDBTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jDBTextFieldData = new lib.jdb.control.jdbtextfield.JDBTextField();
        jLabel5 = new javax.swing.JLabel();
        jButtonSelTitulo = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jButtonSelPrograma = new javax.swing.JButton();
        jButtonSelEditora = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jDBTextArea1 = new lib.jdb.control.jdbtextarea.JDBTextArea();
        jLabel6 = new javax.swing.JLabel();
        jDBTextField6 = new lib.jdb.control.jdbtextfield.JDBTextField();
        jDBCheckBox1 = new lib.jdb.control.jdbcheckbox.JDBCheckBox();
        jDBComboBox1 = new lib.jdb.control.jdbcombobox.JDBComboBox();
        jLabel9 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButtonSelecionar = new javax.swing.JButton();
        jDBButtonDelete1 = new lib.jdb.control.jdbbuttondelete.JDBButtonDelete();
        jDBTextFieldIdTitulo = new lib.jdb.control.jdbtextfield.JDBTextField();
        jDBTextFieldTitulo = new lib.jdb.control.jdbtextfield.JDBTextField();
        jDBButtonFirst1 = new lib.jdb.control.jdbbuttonfirst.JDBButtonFirst();
        jDBButtonPrevious1 = new lib.jdb.control.jdbbuttonprevious.JDBButtonPrevious();
        jDBButtonNext1 = new lib.jdb.control.jdbbuttonnext.JDBButtonNext();
        jDBButtonLast1 = new lib.jdb.control.jdbbuttonlast.JDBButtonLast();
        jSeparator2 = new javax.swing.JSeparator();
        jDBTextFieldIdEditora = new lib.jdb.control.jdbtextfield.JDBTextField();
        jDBTextFieldEditora = new lib.jdb.control.jdbtextfield.JDBTextField();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jDBTextFieldPrograma = new lib.jdb.control.jdbtextfield.JDBTextField();
        jDBTextFieldIdPrograma = new lib.jdb.control.jdbtextfield.JDBTextField();
        jDBTextField7 = new lib.jdb.control.jdbtextfield.JDBTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jDBLookUpComboBox1 = new lib.jdb.control.jdblookupcombobox.JDBLookUpComboBox();
        jButtonevolver = new javax.swing.JButton();
        jDBLabelCount1 = new lib.jdb.control.jdblabelcount.JDBLabelCount();
        jLabelPosicao = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem7 = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItemAssuntosLidos = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenuItem6 = new javax.swing.JMenuItem();

        jDBQueryLivros.setSQL("select * from livro");
        jDBQueryLivros.setSaveManually(true);
        jDBQueryLivros.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                jDBQueryLivrosPropertyChange(evt);
            }
        });
        jDBQueryLivros.addSaveManuallyEventListener(new lib.jdb.jdbquery.event.SaveManuallyEventListener() {
            public void onSaveManually(lib.jdb.jdbquery.event.SaveManuallyEventObject evt) {
                jDBQueryLivrosOnSaveManually(evt);
            }
        });
        jDBQueryLivros.addScrollEventListener(new lib.jdb.jdbquery.event.ScrollEventListener() {
            public void beforeScroll(lib.jdb.jdbquery.event.ScrollEventObject evt) {
            }
            public void afterScroll(lib.jdb.jdbquery.event.ScrollEventObject evt) {
                jDBQueryLivrosAfterScroll(evt);
            }
        });

        jDBQueryTitulo.setSQL("select t.id, t.titulo, a.assunto, t.resenha, a.categoriaprateleira_id\n from titulo t  \ninner join assunto a on t.assunto_id = a.id\n");
        jDBQueryTitulo.addExecQueryEventListener(new lib.jdb.jdbquery.event.ExecQueryEventListener() {
            public void beforeExecQuery(lib.jdb.jdbquery.event.ExecQueryEventObject evt) {
            }
            public void afterExecQuery(lib.jdb.jdbquery.event.ExecQueryEventObject evt) {
                jDBQueryTituloAfterExecQuery(evt);
            }
        });

        jDBQueryEditora.setSQL("select * from editora");

        jDBQueryPrograma.setSQL("select * from programa");

        jDBQueryPrateleira.setSQL("select * from prateleira");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Livros");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });
        addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                formKeyReleased(evt);
            }
        });

        jDBButtonNew1.setJDBQuery(jDBQueryLivros);
        jDBButtonNew1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jDBButtonNew1ActionPerformed(evt);
            }
        });

        jDBButtonSave1.setJDBQuery(jDBQueryLivros);
        jDBButtonSave1.setEnabled(false);

        jDBButtonCancel1.setJDBQuery(jDBQueryLivros);
        jDBButtonCancel1.setEnabled(false);

        jLabel1.setText("Código / Título");

        jDBTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jDBTable1.setJDBQuery(jDBQueryLivros);
        jDBTable1.setEditable(false);
        jDBTable1.setInvisibleFields("disponivel editora_id programa_id titulo_id baixa reserva_id prateleira_id");
        jDBTable1.setjDBTableStyle(jDBTableStyle1);
        jScrollPane1.setViewportView(jDBTable1);

        jDBTextField3.setJDBQuery(jDBQueryLivros);
        jDBTextField3.setFieldName("edicao");
        jDBTextField3.setjDBControlStyle(jDBControlStyle1);

        jLabel3.setText("Edição");

        jLabel4.setText("Código / Editora");

        jDBTextFieldData.setJDBQuery(jDBQueryLivros);
        jDBTextFieldData.setFieldName("data_aquisicao");
        jDBTextFieldData.setjDBControlStyle(jDBControlStyle1);

        jLabel5.setText("Data Aquisição");

        jButtonSelTitulo.setText("...");
        jButtonSelTitulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSelTituloActionPerformed(evt);
            }
        });

        jLabel7.setText("Código / Programa");

        jButtonSelPrograma.setText("...");
        jButtonSelPrograma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSelProgramaActionPerformed(evt);
            }
        });

        jButtonSelEditora.setText("...");
        jButtonSelEditora.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSelEditoraActionPerformed(evt);
            }
        });

        jLabel8.setText("Observação");

        jDBTextArea1.setJDBQuery(jDBQueryLivros);
        jDBTextArea1.setFieldName("obs");
        jDBTextArea1.setjDBControlStyle(jDBControlStyle1);

        jLabel6.setText("ISBN");

        jDBTextField6.setJDBQuery(jDBQueryLivros);
        jDBTextField6.setFieldName("isbn");
        jDBTextField6.setjDBControlStyle(jDBControlStyle1);

        jDBCheckBox1.setJDBQuery(jDBQueryLivros);
        jDBCheckBox1.setFieldName("disponivel");
        jDBCheckBox1.setText("Disponível");

        jDBComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { " ", "Extraviado", "Danificado" }));
        jDBComboBox1.setJDBQuery(jDBQueryLivros);
        jDBComboBox1.setFieldName("baixa");
        jDBComboBox1.setjDBControlStyle(jDBControlStyle1);

        jLabel9.setText("Baixa");

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/quit.png"))); // NOI18N
        jButton1.setText("Fechar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButtonSelecionar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/acpt.png"))); // NOI18N
        jButtonSelecionar.setText("Selecionar");
        jButtonSelecionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSelecionarActionPerformed(evt);
            }
        });

        jDBButtonDelete1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones.png"))); // NOI18N
        jDBButtonDelete1.setJDBQuery(jDBQueryLivros);

        jDBTextFieldIdTitulo.setJDBQuery(jDBQueryLivros);
        jDBTextFieldIdTitulo.setFieldName("titulo_id");
        jDBTextFieldIdTitulo.setjDBControlStyle(jDBControlStyle1);
        jDBTextFieldIdTitulo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jDBTextFieldIdTituloKeyReleased(evt);
            }
        });

        jDBTextFieldTitulo.setEditable(false);
        jDBTextFieldTitulo.setJDBQuery(jDBQueryTitulo);
        jDBTextFieldTitulo.setFieldName("titulo");

        jDBButtonFirst1.setJDBQuery(jDBQueryLivros);
        jDBButtonFirst1.setText("");

        jDBButtonPrevious1.setJDBQuery(jDBQueryLivros);
        jDBButtonPrevious1.setText("");

        jDBButtonNext1.setJDBQuery(jDBQueryLivros);
        jDBButtonNext1.setText("");

        jDBButtonLast1.setJDBQuery(jDBQueryLivros);
        jDBButtonLast1.setText("");

        jSeparator2.setOrientation(javax.swing.SwingConstants.VERTICAL);

        jDBTextFieldIdEditora.setJDBQuery(jDBQueryLivros);
        jDBTextFieldIdEditora.setFieldName("editora_id");
        jDBTextFieldIdEditora.setjDBControlStyle(jDBControlStyle1);
        jDBTextFieldIdEditora.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jDBTextFieldIdEditoraKeyReleased(evt);
            }
        });

        jDBTextFieldEditora.setEditable(false);
        jDBTextFieldEditora.setJDBQuery(jDBQueryEditora);
        jDBTextFieldEditora.setFieldName("editora");
        jDBTextFieldEditora.setjDBControlStyle(jDBControlStyle1);

        jDateChooser1.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                jDateChooser1PropertyChange(evt);
            }
        });

        jDBTextFieldPrograma.setEditable(false);
        jDBTextFieldPrograma.setJDBQuery(jDBQueryPrograma);
        jDBTextFieldPrograma.setFieldName("programa");
        jDBTextFieldPrograma.setjDBControlStyle(jDBControlStyle1);

        jDBTextFieldIdPrograma.setJDBQuery(jDBQueryLivros);
        jDBTextFieldIdPrograma.setFieldName("programa_id");
        jDBTextFieldIdPrograma.setjDBControlStyle(jDBControlStyle1);
        jDBTextFieldIdPrograma.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jDBTextFieldIdProgramaKeyReleased(evt);
            }
        });

        jDBTextField7.setJDBQuery(jDBQueryLivros);
        jDBTextField7.setFieldName("volume");
        jDBTextField7.setjDBControlStyle(jDBControlStyle1);

        jLabel10.setText("Volume");

        jLabel11.setText("Prateleira");

        jDBLookUpComboBox1.setJDBListQuery(jDBQueryPrateleira);
        jDBLookUpComboBox1.setJDBQuery(jDBQueryLivros);
        jDBLookUpComboBox1.setInvisibleFields("id");
        jDBLookUpComboBox1.setjDBControlStyle(jDBControlStyle1);
        jDBLookUpComboBox1.setKeyField("prateleira_id");
        jDBLookUpComboBox1.setKeyListField("id");

        jButtonevolver.setIcon(new javax.swing.ImageIcon(getClass().getResource("/return.png"))); // NOI18N
        jButtonevolver.setText("Devolver");
        jButtonevolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonevolverActionPerformed(evt);
            }
        });

        jDBLabelCount1.setjDBQuery(jDBQueryLivros);
        jDBLabelCount1.setText("wewer");

        jLabelPosicao.setText("Posição: 0 / ");

        jMenu1.setText("Pesquisar");

        jMenuItem7.setText("Livros por Autor");
        jMenuItem7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem7ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem7);

        jMenuItem1.setText("Livros por Título");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuItem3.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_T, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem3.setText("Livros por Tombo");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem3);

        jMenuItem2.setText("Livros por Programa");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Relatórios");

        jMenuItem4.setText("Top Emprestados");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem4);

        jMenuItemAssuntosLidos.setText("Top Assuntos Mais Lidos");
        jMenuItemAssuntosLidos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemAssuntosLidosActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItemAssuntosLidos);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Ferramentas");

        jMenu4.setText("Assistente de geração de Código de Barras");

        jMenuItem5.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_1, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem5.setText("Adicionar a Seleção");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem5);

        jMenuItem6.setText("Limpar Lista");
        jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem6ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem6);

        jMenu3.add(jMenu4);

        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jDBTextField3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jDBTextFieldIdEditora, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jDBTextFieldEditora, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel4)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jButtonSelEditora)))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jDBTextFieldData, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jLabel5))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel7)
                                        .addGap(4, 4, 4)
                                        .addComponent(jButtonSelPrograma))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jDBTextFieldIdPrograma, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jDBTextFieldPrograma, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addComponent(jLabel10)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jDBTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jDBComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel9)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jDBCheckBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel11)
                                    .addComponent(jDBLookUpComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 328, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 231, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1)
                            .addComponent(jDBTextArea1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel1)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jButtonSelTitulo))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jDBTextFieldIdTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jDBTextFieldTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 408, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGap(24, 24, 24)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel6)
                                            .addComponent(jDBTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addComponent(jLabel8)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jDBButtonNew1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jDBButtonSave1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jDBButtonDelete1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jDBButtonCancel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jDBButtonFirst1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jDBButtonPrevious1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(jLabelPosicao)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jDBLabelCount1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(62, 62, 62)
                                                .addComponent(jDBButtonNext1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jDBButtonLast1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGap(18, 18, 18)
                                        .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jButtonSelecionar)
                                                .addGap(17, 17, 17)
                                                .addComponent(jButtonevolver))
                                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButtonevolver, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addComponent(jButtonSelecionar, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jDBButtonSave1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jDBButtonDelete1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                                    .addComponent(jDBButtonCancel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jDBButtonNew1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jDBButtonLast1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabelPosicao)
                                        .addComponent(jDBLabelCount1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jDBButtonFirst1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jDBButtonPrevious1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jDBButtonNext1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jButtonSelTitulo))
                        .addGap(3, 3, 3)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jDBTextFieldIdTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jDBTextFieldTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jDBTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(33, 33, 33)))
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel3)
                                    .addComponent(jButtonSelEditora)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel7)
                                    .addComponent(jButtonSelPrograma))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jDBTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jDBTextFieldIdEditora, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jDBTextFieldEditora, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jDBTextFieldData, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(jLabel9)
                            .addComponent(jDBCheckBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jDBTextFieldIdPrograma, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jDBTextFieldPrograma, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jDBComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jDBTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jDBLookUpComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addComponent(jLabel8)
                .addGap(0, 0, 0)
                .addComponent(jDBTextArea1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 115, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonSelEditoraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSelEditoraActionPerformed
        JFEditora je = new JFEditora(jDBQueryLivros.getJDBConnection());
        je.show();
        je.addWindowListener(new WindowListener() {
            @Override public void windowOpened(WindowEvent e) {}
            @Override public void windowClosing(WindowEvent e) {            }
            @Override public void windowClosed(WindowEvent e) {
                if(je.selecionar){
                    jDBQueryEditora.setSQL(qryEditora+" where id = "+je.getId());
                    jDBQueryEditora.execQuery();
                    jDBTextFieldIdEditora.setText(je.getId());
                    jDBQueryLivros.edit();
                }
            }
            @Override public void windowIconified(WindowEvent e) {}
            @Override public void windowDeiconified(WindowEvent e) {}
            @Override public void windowActivated(WindowEvent e) {}
            @Override public void windowDeactivated(WindowEvent e) {}
        });
    }//GEN-LAST:event_jButtonSelEditoraActionPerformed

    private void jButtonSelTituloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSelTituloActionPerformed
        JFTitulos jt = new JFTitulos(jDBQueryLivros.getJDBConnection(),true);
        jt.show();
        jt.addWindowListener(new WindowListener() {
            @Override public void windowOpened(WindowEvent e) {}
            @Override public void windowClosing(WindowEvent e) {            }
            @Override public void windowClosed(WindowEvent e) {
                if(jt.selecionar){
                    jDBQueryTitulo.setSQL("select concat(t.titulo,\" | \",au.autor,\" | \",a.assunto) as titulo from titulo t "
                            + "inner join assunto a on t.assunto_id = a.id "
                            + "inner join autor au on t.autor_id = au.id "
                            + "where t.id = "+jt.getID());
                    jDBQueryTitulo.execQuery();
                    jDBTextFieldIdTitulo.setText(jt.getID());
                    jDBQueryLivros.edit();
                }
            }
            @Override public void windowIconified(WindowEvent e) {}
            @Override public void windowDeiconified(WindowEvent e) {}
            @Override public void windowActivated(WindowEvent e) {}
            @Override public void windowDeactivated(WindowEvent e) {}
        });
    }//GEN-LAST:event_jButtonSelTituloActionPerformed

    private void jButtonSelProgramaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSelProgramaActionPerformed
        JFPrograma jp = new JFPrograma(jDBQueryLivros.getJDBConnection());
        jp.setSelecionarVisible();
        jp.show();
        jp.addWindowListener(new WindowListener() {
            @Override public void windowOpened(WindowEvent e) {}
            @Override public void windowClosing(WindowEvent e) {            }
            @Override public void windowClosed(WindowEvent e) {
                if(jp.selecionar){
                    jDBQueryPrograma.setSQL(qryPrograma+" where id = "+jp.getID());
                    jDBQueryPrograma.execQuery();
                    jDBTextFieldIdPrograma.setText(jp.getID());
                    jDBQueryLivros.edit();
                }
            }
            @Override public void windowIconified(WindowEvent e) {}
            @Override public void windowDeiconified(WindowEvent e) {}
            @Override public void windowActivated(WindowEvent e) {}
            @Override public void windowDeactivated(WindowEvent e) {}
        });
    }//GEN-LAST:event_jButtonSelProgramaActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButtonSelecionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSelecionarActionPerformed
        selecionar=true;
        this.dispose();
    }//GEN-LAST:event_jButtonSelecionarActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        jDBQueryLivros.setSQL(qryLivros+" and id = "+
                JOptionPane.showInputDialog("Digite o Tombo"));
        jDBQueryLivros.execQuery();
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jDBQueryLivrosAfterScroll(lib.jdb.jdbquery.event.ScrollEventObject evt) {//GEN-FIRST:event_jDBQueryLivrosAfterScroll
        jDBQueryTitulo.setSQL(qryTitulo
                            + " where t.id = "+jDBQueryLivros.getCurrentFieldValue("titulo_id"));
                    jDBQueryTitulo.execQuery();
        jDBQueryEditora.setSQL(qryEditora+" where id ="+jDBQueryLivros.getCurrentFieldValue("editora_id"));
        jDBQueryEditora.execQuery();
        jDBQueryPrograma.setSQL(qryPrograma+" where id ="+jDBQueryLivros.getCurrentFieldValue("programa_id"));
        jDBQueryPrograma.execQuery();
        if(!jDBQueryLivros.getCurrentFieldValueAsBoolean("disponivel")){
            jButtonevolver.setEnabled(true);
        }else{
            jButtonevolver.setEnabled(false);
        }
        jLabelPosicao.setText("Posição: "+Integer.toString(jDBQueryLivros.getRow())+" / ");
    }//GEN-LAST:event_jDBQueryLivrosAfterScroll

    private void formKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_formKeyReleased
        if(jDBTextFieldIdTitulo.getText().matches("\\d+")){
            jDBQueryTitulo.setSQL(qryTitulo+" where id ="+jDBTextFieldIdTitulo.getText());
            jDBQueryTitulo.execQuery();
        }
    }//GEN-LAST:event_formKeyReleased

    private void jDBTextFieldIdTituloKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jDBTextFieldIdTituloKeyReleased
        if(jDBTextFieldIdTitulo.getText().matches("\\d+")){
            jDBQueryTitulo.setSQL(qryTitulo+" where t.id ="+jDBTextFieldIdTitulo.getText());
            jDBQueryTitulo.execQuery();
            jDBQueryPrateleira.setSQL(qryPrateleira+" where categoria_prateleira_id ="+
                    jDBQueryTitulo.getCurrentFieldValue("categoriaprateleira_id"));
            jDBQueryPrateleira.execQuery();
        }
        else{
            jDBQueryTitulo.setSQL(qryTitulo+" where t.id =0");
            jDBQueryTitulo.execQuery();
        }
    }//GEN-LAST:event_jDBTextFieldIdTituloKeyReleased

    private void jDBTextFieldIdEditoraKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jDBTextFieldIdEditoraKeyReleased
        if(jDBTextFieldIdEditora.getText().matches("\\d+")){
            jDBQueryEditora.setSQL(qryEditora+" where id ="+jDBTextFieldIdEditora.getText());
            jDBQueryEditora.execQuery();
        }else{
            jDBQueryEditora.setSQL(qryEditora+" where id = 0");
            jDBQueryEditora.execQuery();
        }
    }//GEN-LAST:event_jDBTextFieldIdEditoraKeyReleased

    private void jDateChooser1PropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jDateChooser1PropertyChange
        if(evt.getPropertyName().equals("date")){
            jDBTextFieldData.setText(jDateChooser1.getJCalendar().getDate().toLocaleString().split(" ")[0]);
            jDBQueryLivros.edit();
            jDBQueryLivros.setNewCurrentFieldValue("data_aquisicao", jDBTextFieldData.getText());
        }
    }//GEN-LAST:event_jDateChooser1PropertyChange

    private void jDBQueryLivrosOnSaveManually(lib.jdb.jdbquery.event.SaveManuallyEventObject evt) {//GEN-FIRST:event_jDBQueryLivrosOnSaveManually
        String msgError="" ;
        if(jDBTextFieldIdTitulo.getText().isEmpty()){
            msgError+="Escolha um Título!\n";
        }
        if(jDBTextFieldIdEditora.getText().isEmpty()){
            msgError+="Escolha uma Editora!\n";
        }
        if(jDBTextFieldIdPrograma.getText().isEmpty()){
            msgError+="Escolha um Programa!\n";
        }
        if(jDBQueryLivros.isInserting())jDBQueryLivros.setNewCurrentFieldValue("reserva_id", null);
        if(msgError.isEmpty()) jDBQueryLivros.save();
        else JOptionPane.showMessageDialog(null, msgError);
    }//GEN-LAST:event_jDBQueryLivrosOnSaveManually

    private void jDBTextFieldIdProgramaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jDBTextFieldIdProgramaKeyReleased
        if(jDBTextFieldIdPrograma.getText().matches("\\d")){
            jDBQueryPrograma.setSQL(qryPrograma+" where id ="+jDBTextFieldIdPrograma.getText());
            jDBQueryPrograma.execQuery();
        }else{
            jDBQueryPrograma.setSQL(qryPrograma+" where id = 0");
            jDBQueryPrograma.execQuery();
        }
    }//GEN-LAST:event_jDBTextFieldIdProgramaKeyReleased

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        Conexao con;
        ResultSet rs;
        con = new Conexao(jDBQueryLivros.getJDBConnection().getConnection());
        try{
            con.Preparar("select t.titulo as \"Título\", au.autor as \"Autor\", a.assunto as \"Assunto\", count(*) as Emprestimos from titulo t " +
                " inner join livro l on t.id = l.titulo_id " +
                " inner join assunto a on a.id = t.assunto_id " +
                " inner join autor au on au.id = t.autor_id " +
                " inner join emprestimo_livros el on el.livro_id = l.id " +
                " group by t.id " +
                " order by Emprestimos desc limit 10");
            rs = con.RetornaDados(new Object[]{});
            JasperPrint jp = JasperFillManager.fillReport(Principal.relPath+"RelatorioLivrosEmprestadissimos.jasper", null, 
                    new JRResultSetDataSource(rs));
             JasperViewer.viewReport(jp,false);
        }
        catch(Exception e){ JOptionPane.showMessageDialog(null, e);}
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jMenuItemAssuntosLidosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemAssuntosLidosActionPerformed
        Conexao con;
        ResultSet rs;
        con = new Conexao(jDBQueryLivros.getJDBConnection().getConnection());
        try{
            con.Preparar("select a.id as \"Cod\", a.assunto as \"Assunto\", count(*) \"Empréstimos\" from assunto a " +
                " inner join titulo t on a.id = t.assunto_id " +
                " inner join livro l on t.id = l.titulo_id " +
                " inner join emprestimo_livros el on el.livro_id = l.id " +
                " group by a.id " +
                " order by a.assunto asc limit 10");
            rs = con.RetornaDados(new Object[]{});
            JasperPrint jp = JasperFillManager.fillReport(Principal.relPath+"RelatorioAssuntosMaisLidos.jasper", null, 
                    new JRResultSetDataSource(rs));
             JasperViewer.viewReport(jp,false);
        }
        catch(Exception e){ JOptionPane.showMessageDialog(null, e);}
    }//GEN-LAST:event_jMenuItemAssuntosLidosActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        jDBQueryLivros.setSQL(qryLivros+" and titulo_id in( "+
                "select t.id from titulo t inner join autor a on t.autor_id = a.id"
                + " where t.titulo like \"%"+JOptionPane.showInputDialog("Digite o Título")+"%\""
                +")");
        jDBQueryLivros.execQuery();
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jDBButtonNew1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jDBButtonNew1ActionPerformed
        jDBTextFieldEditora.setText("");
        jDBTextFieldPrograma.setText("");
        jDBTextFieldTitulo.setText("");
    }//GEN-LAST:event_jDBButtonNew1ActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        if(ja==null){
            ja = new JFAssistenteCodBarras(this);
            ja.setLocation((int)this.getSize().getWidth()+10, 0);
        }
        if(ja.checkIDNotOnList(jDBQueryLivros.getCurrentFieldValue("id"))){
            ja.addCod(jDBQueryLivros.getCurrentFieldValue("id")+"- "+jDBTextFieldTitulo.getText());
            ja.setVisible(true);
        }else{
            JOptionPane.showMessageDialog(null, "Este livro já está na lista para ser impresso.");
        }
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        if(ja!=null)ja.dispose();
    }//GEN-LAST:event_formWindowClosed

    private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem6ActionPerformed
        if(ja!=null) ja.limparLista();
    }//GEN-LAST:event_jMenuItem6ActionPerformed

    private void jMenuItem7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem7ActionPerformed
        jDBQueryLivros.setSQL(qryLivros+" and id in( "+
                "select li.id from livro li inner join titulo t on t.id = li.titulo_id "
                + " inner join autor a on t.autor_id = a.id "
                + " where a.autor like \"%"+JOptionPane.showInputDialog("Digite o nome do Autor")+"%\""
                +")");
        jDBQueryLivros.execQuery();
    }//GEN-LAST:event_jMenuItem7ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        jDBQueryLivros.setSQL(qryLivros+" and programa_id in( "+
                "select id from programa "
                + " where programa like \"%"+JOptionPane.showInputDialog("Digite o Programa")+"%\""
                +")");
        jDBQueryLivros.execQuery();
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jDBQueryTituloAfterExecQuery(lib.jdb.jdbquery.event.ExecQueryEventObject evt) {//GEN-FIRST:event_jDBQueryTituloAfterExecQuery
        jDBQueryPrateleira.setSQL(qryPrateleira+" where categoria_prateleira_id="+
                jDBQueryTitulo.getCurrentFieldValue("categoriaprateleira_id"));
        jDBQueryPrateleira.execQuery();
    }//GEN-LAST:event_jDBQueryTituloAfterExecQuery

    private void jButtonevolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonevolverActionPerformed
        String id = jDBQueryLivros.getCurrentFieldValue("id"), msg;
        jDBUpdateTransaction1.setSQL("update emprestimo_livros set data_devolucao = curdate() "
                + " where livro_id = "+id+" and data_devolucao is null;");
        try {
            if(jDBUpdateTransaction1.execUpdate()){
                jDBQueryLivros.execQuery();
                jDBQueryLivros.locate(id, id, true);
                msg = "Devolução registrada com sucesso!";
            }else{
                msg = "Ocorreu um erro durante o registro.";
            }
            JOptionPane.showMessageDialog(null,msg);
        }catch (SQLException ex) {
            Logger.getLogger(JFLivros.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButtonevolverActionPerformed

    private void jDBQueryLivrosPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jDBQueryLivrosPropertyChange
        jDBButtonDelete1.setEnabled(!jDBQueryLivros.isInserting()&&!jDBQueryLivros.isEditing());
        jDBButtonNew1.setEnabled(!jDBQueryLivros.isInserting()&&!jDBQueryLivros.isEditing());
        jDBButtonNext1.setEnabled(!jDBQueryLivros.isInserting()&&!jDBQueryLivros.isEditing()&&
                jDBQueryLivros.getRow()<jDBQueryLivros.getQueryQuantity());
        jDBButtonLast1.setEnabled(!jDBQueryLivros.isInserting()&&
                                !jDBQueryLivros.isEditing()&&
                jDBQueryLivros.getRow()<jDBQueryLivros.getQueryQuantity());
        jDBButtonPrevious1.setEnabled(!jDBQueryLivros.isInserting()&&!jDBQueryLivros.isEditing()&&
                jDBQueryLivros.getRow()>1);
        jDBButtonFirst1.setEnabled(!jDBQueryLivros.isInserting()&&!jDBQueryLivros.isEditing()&&
                jDBQueryLivros.getRow()>1);
        jDBButtonSave1.setEnabled(jDBQueryLivros.isEditing() || jDBQueryLivros.isInserting());
        jDBButtonCancel1.setEnabled(jDBQueryLivros.isEditing() || jDBQueryLivros.isInserting());
        
    }//GEN-LAST:event_jDBQueryLivrosPropertyChange

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFLivros().setVisible(true);
            }
        });
    }
    
    public JDBConnection getJDBConnection(){
        return jDBQueryLivros.getJDBConnection();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButtonSelEditora;
    private javax.swing.JButton jButtonSelPrograma;
    private javax.swing.JButton jButtonSelTitulo;
    private javax.swing.JButton jButtonSelecionar;
    private javax.swing.JButton jButtonevolver;
    private lib.jdb.control.jdbbuttoncancel.JDBButtonCancel jDBButtonCancel1;
    private lib.jdb.control.jdbbuttondelete.JDBButtonDelete jDBButtonDelete1;
    private lib.jdb.control.jdbbuttonfirst.JDBButtonFirst jDBButtonFirst1;
    private lib.jdb.control.jdbbuttonlast.JDBButtonLast jDBButtonLast1;
    private lib.jdb.control.jdbbuttonnew.JDBButtonNew jDBButtonNew1;
    private lib.jdb.control.jdbbuttonnext.JDBButtonNext jDBButtonNext1;
    private lib.jdb.control.jdbbuttonprevious.JDBButtonPrevious jDBButtonPrevious1;
    private lib.jdb.control.jdbbuttonsave.JDBButtonSave jDBButtonSave1;
    private lib.jdb.control.jdbcheckbox.JDBCheckBox jDBCheckBox1;
    private lib.jdb.control.jdbcombobox.JDBComboBox jDBComboBox1;
    private lib.jdb.control.jdbcontrolstyle.JDBControlStyle jDBControlStyle1;
    private lib.jdb.control.jdblabelcount.JDBLabelCount jDBLabelCount1;
    private lib.jdb.control.jdblookupcombobox.JDBLookUpComboBox jDBLookUpComboBox1;
    private lib.jdb.jdbquery.JDBQuery jDBQueryEditora;
    private lib.jdb.jdbquery.JDBQuery jDBQueryLivros;
    private lib.jdb.jdbquery.JDBQuery jDBQueryPrateleira;
    private lib.jdb.jdbquery.JDBQuery jDBQueryPrograma;
    private lib.jdb.jdbquery.JDBQuery jDBQueryTitulo;
    private lib.jdb.control.jdbtable.JDBTable jDBTable1;
    private lib.jdb.control.jdbtable.JDBTableStyle jDBTableStyle1;
    private lib.jdb.control.jdbtextarea.JDBTextArea jDBTextArea1;
    private lib.jdb.control.jdbtextfield.JDBTextField jDBTextField3;
    private lib.jdb.control.jdbtextfield.JDBTextField jDBTextField6;
    private lib.jdb.control.jdbtextfield.JDBTextField jDBTextField7;
    private lib.jdb.control.jdbtextfield.JDBTextField jDBTextFieldData;
    private lib.jdb.control.jdbtextfield.JDBTextField jDBTextFieldEditora;
    private lib.jdb.control.jdbtextfield.JDBTextField jDBTextFieldIdEditora;
    private lib.jdb.control.jdbtextfield.JDBTextField jDBTextFieldIdPrograma;
    private lib.jdb.control.jdbtextfield.JDBTextField jDBTextFieldIdTitulo;
    private lib.jdb.control.jdbtextfield.JDBTextField jDBTextFieldPrograma;
    private lib.jdb.control.jdbtextfield.JDBTextField jDBTextFieldTitulo;
    private lib.jdb.jdbupdatetransaction.JDBUpdateTransaction jDBUpdateTransaction1;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelPosicao;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItemAssuntosLidos;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator2;
    // End of variables declaration//GEN-END:variables

    String getId() {
        return jDBQueryLivros.getCurrentFieldValue("id");
    }
    
    boolean isDisponivel(){
        return jDBQueryLivros.getCurrentFieldValueAsBoolean("disponivel");
    }
}
