
import java.awt.event.WindowEvent;
import java.awt.event.WindowListener;
import javax.swing.JOptionPane;
import lib.jdb.connection.JDBConnection;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author vmf
 */
public class JFTitulos extends javax.swing.JFrame {
    public boolean selecionar = false;
    String qryAutor = "select * from autor ", 
            qryAssunto = "select * from assunto ";

    /**
     * Creates new form JFAluno
     */
    public JFTitulos() {
        initComponents();
        jButtonSelecionar.setVisible(false);
        jDBTable1.setFieldsTitle("id", "Cod.");
        jDBTable1.setFieldsTitle("titulo", "Título");
        jDBTable1.setFieldsTitle("resenha", "Resenha");
        CustomTable.setDefaulttable(jDBTable1);
    }
    public JFTitulos(JDBConnection jdb) {
        this();
        jDBQueryTitulos.setJDBConnection(jdb);
        jDBQueryAssunto.setJDBConnection(jdb);
        jDBQueryAutor.setJDBConnection(jdb);
        jDBQueryTitulos.execQuery();
    }
    public JFTitulos(JDBConnection jdb, boolean selecionar) {
        this();
        jDBQueryTitulos.setJDBConnection(jdb);
        jDBQueryAssunto.setJDBConnection(jdb);
        jDBQueryAutor.setJDBConnection(jdb);
        jDBQueryTitulos.execQuery();
        if(selecionar) jButtonSelecionar.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDBQueryTitulos = new lib.jdb.jdbquery.JDBQuery();
        jDBControlStyle1 = new lib.jdb.control.jdbcontrolstyle.JDBControlStyle();
        jDBQueryAssunto = new lib.jdb.jdbquery.JDBQuery();
        jDBLookUpField1 = new lib.jdb.control.jdblookupfield.JDBLookUpField();
        jDBTableStyle1 = new lib.jdb.control.jdbtable.JDBTableStyle();
        jDBQueryAutor = new lib.jdb.jdbquery.JDBQuery();
        jDBTextFieldTitulo = new lib.jdb.control.jdbtextfield.JDBTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jDBTable1 = new lib.jdb.control.jdbtable.JDBTable();
        jLabel8 = new javax.swing.JLabel();
        jDBTextArea1 = new lib.jdb.control.jdbtextarea.JDBTextArea();
        jButtonSelAssunto = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jButtonSelAssunto1 = new javax.swing.JButton();
        jDBTextFieldAutorId = new lib.jdb.control.jdbtextfield.JDBTextField();
        jDBTextFieldTitulo1 = new lib.jdb.control.jdbtextfield.JDBTextField();
        jDBTextFieldAssunto = new lib.jdb.control.jdbtextfield.JDBTextField();
        jDBTextFieldAssuntoId = new lib.jdb.control.jdbtextfield.JDBTextField();
        jToolBar1 = new javax.swing.JToolBar();
        jDBButtonNew1 = new lib.jdb.control.jdbbuttonnew.JDBButtonNew();
        jDBButtonSave1 = new lib.jdb.control.jdbbuttonsave.JDBButtonSave();
        jDBButtonCancel1 = new lib.jdb.control.jdbbuttoncancel.JDBButtonCancel();
        jDBButtonDelete1 = new lib.jdb.control.jdbbuttondelete.JDBButtonDelete();
        jToolBar2 = new javax.swing.JToolBar();
        jDBButtonFirst1 = new lib.jdb.control.jdbbuttonfirst.JDBButtonFirst();
        jDBButtonPrevious1 = new lib.jdb.control.jdbbuttonprevious.JDBButtonPrevious();
        jLabelPosicao = new javax.swing.JLabel();
        jDBLabelCount1 = new lib.jdb.control.jdblabelcount.JDBLabelCount();
        jDBButtonNext1 = new lib.jdb.control.jdbbuttonnext.JDBButtonNext();
        jDBButtonLast1 = new lib.jdb.control.jdbbuttonlast.JDBButtonLast();
        jToolBar3 = new javax.swing.JToolBar();
        jButtonSelecionar = new javax.swing.JButton();
        jButtonFechar = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu7 = new javax.swing.JMenu();
        jMenuItem19 = new javax.swing.JMenuItem();
        jMenuItem20 = new javax.swing.JMenuItem();
        jMenuItem21 = new javax.swing.JMenuItem();
        jMenuItem22 = new javax.swing.JMenuItem();
        jSeparator5 = new javax.swing.JPopupMenu.Separator();
        jMenuItem24 = new javax.swing.JMenuItem();
        jMenuItem25 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenu5 = new javax.swing.JMenu();
        jMenuItem8 = new javax.swing.JMenuItem();
        jMenuItem9 = new javax.swing.JMenuItem();
        jMenuItem10 = new javax.swing.JMenuItem();
        jMenuItem11 = new javax.swing.JMenuItem();

        jDBQueryTitulos.setSQL("select * from titulo");
        jDBQueryTitulos.setSaveManually(true);
        jDBQueryTitulos.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                jDBQueryTitulosPropertyChange(evt);
            }
        });
        jDBQueryTitulos.addSaveManuallyEventListener(new lib.jdb.jdbquery.event.SaveManuallyEventListener() {
            public void onSaveManually(lib.jdb.jdbquery.event.SaveManuallyEventObject evt) {
                jDBQueryTitulosOnSaveManually(evt);
            }
        });
        jDBQueryTitulos.addScrollEventListener(new lib.jdb.jdbquery.event.ScrollEventListener() {
            public void beforeScroll(lib.jdb.jdbquery.event.ScrollEventObject evt) {
            }
            public void afterScroll(lib.jdb.jdbquery.event.ScrollEventObject evt) {
                jDBQueryTitulosAfterScroll(evt);
            }
        });

        jDBQueryAssunto.setSQL("select * from assunto");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Titulos");

        jDBTextFieldTitulo.setJDBQuery(jDBQueryTitulos);
        jDBTextFieldTitulo.setFieldName("titulo");
        jDBTextFieldTitulo.setjDBControlStyle(jDBControlStyle1);

        jLabel1.setText("Titulo");

        jLabel2.setText("Código / Assunto");

        jDBTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jDBTable1.setJDBQuery(jDBQueryTitulos);
        jDBTable1.setEditable(false);
        jDBTable1.setInvisibleFields("assunto_id autor_id");
        jDBTable1.setjDBTableStyle(jDBTableStyle1);
        jScrollPane1.setViewportView(jDBTable1);

        jLabel8.setText("Resenha");

        jDBTextArea1.setJDBQuery(jDBQueryTitulos);
        jDBTextArea1.setFieldName("resenha");
        jDBTextArea1.setjDBControlStyle(jDBControlStyle1);

        jButtonSelAssunto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/search.png"))); // NOI18N
        jButtonSelAssunto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSelAssuntoActionPerformed(evt);
            }
        });

        jLabel3.setText("Código / Autor");

        jButtonSelAssunto1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/search.png"))); // NOI18N
        jButtonSelAssunto1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSelAssunto1ActionPerformed(evt);
            }
        });

        jDBTextFieldAutorId.setJDBQuery(jDBQueryTitulos);
        jDBTextFieldAutorId.setFieldName("autor_id");
        jDBTextFieldAutorId.setjDBControlStyle(jDBControlStyle1);
        jDBTextFieldAutorId.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jDBTextFieldAutorIdKeyReleased(evt);
            }
        });

        jDBTextFieldTitulo1.setEditable(false);
        jDBTextFieldTitulo1.setJDBQuery(jDBQueryAutor);
        jDBTextFieldTitulo1.setFieldName("autor");
        jDBTextFieldTitulo1.setjDBControlStyle(jDBControlStyle1);

        jDBTextFieldAssunto.setEditable(false);
        jDBTextFieldAssunto.setJDBQuery(jDBQueryAssunto);
        jDBTextFieldAssunto.setFieldName("assunto");
        jDBTextFieldAssunto.setjDBControlStyle(jDBControlStyle1);

        jDBTextFieldAssuntoId.setJDBQuery(jDBQueryTitulos);
        jDBTextFieldAssuntoId.setFieldName("assunto_id");
        jDBTextFieldAssuntoId.setjDBControlStyle(jDBControlStyle1);
        jDBTextFieldAssuntoId.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jDBTextFieldAssuntoIdKeyReleased(evt);
            }
        });

        jToolBar1.setRollover(true);

        jDBButtonNew1.setJDBQuery(jDBQueryTitulos);
        jDBButtonNew1.setFocusable(false);
        jDBButtonNew1.setHorizontalTextPosition(0);
        jDBButtonNew1.setText("");
        jDBButtonNew1.setToolTipText("Novo");
        jDBButtonNew1.setVerticalTextPosition(3);
        jDBButtonNew1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jDBButtonNew1ActionPerformed(evt);
            }
        });
        jToolBar1.add(jDBButtonNew1);

        jDBButtonSave1.setJDBQuery(jDBQueryTitulos);
        jDBButtonSave1.setFocusable(false);
        jDBButtonSave1.setHorizontalTextPosition(0);
        jDBButtonSave1.setText("");
        jDBButtonSave1.setToolTipText("Salvar");
        jDBButtonSave1.setVerticalTextPosition(3);
        jToolBar1.add(jDBButtonSave1);

        jDBButtonCancel1.setJDBQuery(jDBQueryTitulos);
        jDBButtonCancel1.setFocusable(false);
        jDBButtonCancel1.setHorizontalTextPosition(0);
        jDBButtonCancel1.setText("");
        jDBButtonCancel1.setToolTipText("Cancelar");
        jDBButtonCancel1.setVerticalTextPosition(3);
        jToolBar1.add(jDBButtonCancel1);

        jDBButtonDelete1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/del.png"))); // NOI18N
        jDBButtonDelete1.setJDBQuery(jDBQueryTitulos);
        jDBButtonDelete1.setFocusable(false);
        jDBButtonDelete1.setHorizontalTextPosition(0);
        jDBButtonDelete1.setText("");
        jDBButtonDelete1.setToolTipText("Excluir");
        jDBButtonDelete1.setVerticalTextPosition(3);
        jToolBar1.add(jDBButtonDelete1);

        jToolBar2.setRollover(true);

        jDBButtonFirst1.setJDBQuery(jDBQueryTitulos);
        jDBButtonFirst1.setFocusable(false);
        jDBButtonFirst1.setHorizontalTextPosition(0);
        jDBButtonFirst1.setText("");
        jDBButtonFirst1.setVerticalTextPosition(3);
        jToolBar2.add(jDBButtonFirst1);

        jDBButtonPrevious1.setJDBQuery(jDBQueryTitulos);
        jDBButtonPrevious1.setFocusable(false);
        jDBButtonPrevious1.setHorizontalTextPosition(0);
        jDBButtonPrevious1.setText("");
        jDBButtonPrevious1.setVerticalTextPosition(3);
        jToolBar2.add(jDBButtonPrevious1);

        jLabelPosicao.setText("0 / ");
        jToolBar2.add(jLabelPosicao);

        jDBLabelCount1.setjDBQuery(jDBQueryTitulos);
        jToolBar2.add(jDBLabelCount1);

        jDBButtonNext1.setJDBQuery(jDBQueryTitulos);
        jDBButtonNext1.setFocusable(false);
        jDBButtonNext1.setHorizontalTextPosition(0);
        jDBButtonNext1.setText("");
        jDBButtonNext1.setVerticalTextPosition(3);
        jToolBar2.add(jDBButtonNext1);

        jDBButtonLast1.setJDBQuery(jDBQueryTitulos);
        jDBButtonLast1.setText("");
        jToolBar2.add(jDBButtonLast1);

        jToolBar3.setRollover(true);

        jButtonSelecionar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/confirm.png"))); // NOI18N
        jButtonSelecionar.setToolTipText("Ok");
        jButtonSelecionar.setFocusable(false);
        jButtonSelecionar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonSelecionar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButtonSelecionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSelecionarActionPerformed(evt);
            }
        });
        jToolBar3.add(jButtonSelecionar);

        jButtonFechar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cancel.png"))); // NOI18N
        jButtonFechar.setToolTipText("Fechar");
        jButtonFechar.setFocusable(false);
        jButtonFechar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonFechar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButtonFechar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonFecharActionPerformed(evt);
            }
        });
        jToolBar3.add(jButtonFechar);

        jMenu7.setMnemonic('a');
        jMenu7.setText("Arquivo");

        jMenuItem19.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_N, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem19.setMnemonic('n');
        jMenuItem19.setText("Novo");
        jMenuItem19.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem19ActionPerformed(evt);
            }
        });
        jMenu7.add(jMenuItem19);

        jMenuItem20.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_E, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem20.setMnemonic('e');
        jMenuItem20.setText("Excluir");
        jMenuItem20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem20ActionPerformed(evt);
            }
        });
        jMenu7.add(jMenuItem20);

        jMenuItem21.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem21.setMnemonic('s');
        jMenuItem21.setText("Salvar");
        jMenuItem21.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem21ActionPerformed(evt);
            }
        });
        jMenu7.add(jMenuItem21);

        jMenuItem22.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem22.setMnemonic('c');
        jMenuItem22.setText("Cancelar");
        jMenuItem22.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem22ActionPerformed(evt);
            }
        });
        jMenu7.add(jMenuItem22);
        jMenu7.add(jSeparator5);

        jMenuItem24.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_O, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem24.setMnemonic('o');
        jMenuItem24.setText("Ok");
        jMenuItem24.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem24ActionPerformed(evt);
            }
        });
        jMenu7.add(jMenuItem24);

        jMenuItem25.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem25.setMnemonic('f');
        jMenuItem25.setText("Fechar");
        jMenuItem25.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem25ActionPerformed(evt);
            }
        });
        jMenu7.add(jMenuItem25);

        jMenuBar1.add(jMenu7);

        jMenu2.setMnemonic('p');
        jMenu2.setText("Pesquisar");
        jMenuBar1.add(jMenu2);

        jMenu5.setMnemonic('n');
        jMenu5.setText("Navegação");

        jMenuItem8.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_LEFT, java.awt.event.InputEvent.SHIFT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem8.setText("Primeiro");
        jMenuItem8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem8ActionPerformed(evt);
            }
        });
        jMenu5.add(jMenuItem8);

        jMenuItem9.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_LEFT, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem9.setText("Anterior");
        jMenuItem9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem9ActionPerformed(evt);
            }
        });
        jMenu5.add(jMenuItem9);

        jMenuItem10.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_RIGHT, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem10.setText("Próximo");
        jMenuItem10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem10ActionPerformed(evt);
            }
        });
        jMenu5.add(jMenuItem10);

        jMenuItem11.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_RIGHT, java.awt.event.InputEvent.SHIFT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem11.setText("Ultimo");
        jMenuItem11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem11ActionPerformed(evt);
            }
        });
        jMenu5.add(jMenuItem11);

        jMenuBar1.add(jMenu5);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jToolBar2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jToolBar3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jDBTextFieldAutorId, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jDBTextFieldTitulo1, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 551, Short.MAX_VALUE)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel1)
                                .addComponent(jDBTextFieldTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(18, 18, 18)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jDBTextFieldAssuntoId, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jDBTextFieldAssunto, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel2)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jButtonSelAssunto, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addComponent(jLabel3)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jButtonSelAssunto1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jDBTextArea1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jToolBar2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jToolBar3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonSelAssunto, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel2)
                        .addComponent(jLabel1)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jDBTextFieldAssuntoId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jDBTextFieldAssunto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jDBTextFieldTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButtonSelAssunto1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jDBTextFieldAutorId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jDBTextFieldTitulo1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jDBTextArea1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonSelAssuntoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSelAssuntoActionPerformed
        JFAssunto ja = new JFAssunto(jDBQueryTitulos.getJDBConnection());
        ja.show();
        ja.addWindowListener(new WindowListener() {
            @Override public void windowOpened(WindowEvent e) {}
            @Override public void windowClosing(WindowEvent e) {            }
            @Override public void windowClosed(WindowEvent e) {
                if(ja.selecionar){
                    jDBQueryTitulos.setNewCurrentFieldValue("assunto_id", ja.getId());
                    jDBTextFieldAssuntoId.setText(ja.getId());
                    jDBQueryTitulos.edit();
                    jDBQueryAssunto.setSQL(qryAssunto+" where id ="+ja.getId());
                    jDBQueryAssunto.execQuery();
                }
            }
            @Override public void windowIconified(WindowEvent e) {}
            @Override public void windowDeiconified(WindowEvent e) {}
            @Override public void windowActivated(WindowEvent e) {}
            @Override public void windowDeactivated(WindowEvent e) {}
        });
    }//GEN-LAST:event_jButtonSelAssuntoActionPerformed

    private void jDBButtonNew1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jDBButtonNew1ActionPerformed
        
    }//GEN-LAST:event_jDBButtonNew1ActionPerformed

    private void jButtonSelecionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSelecionarActionPerformed
        selecionar=true;
        this.dispose();
    }//GEN-LAST:event_jButtonSelecionarActionPerformed

    private void jButtonFecharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonFecharActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButtonFecharActionPerformed

    private void jButtonSelAssunto1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSelAssunto1ActionPerformed
        JFAutor ja = new JFAutor(jDBQueryTitulos.getJDBConnection());
        ja.show();
        ja.addWindowListener(new WindowListener() {
            @Override public void windowOpened(WindowEvent e) {}
            @Override public void windowClosing(WindowEvent e) {            }
            @Override public void windowClosed(WindowEvent e) {
                if(ja.selecionar){
                    jDBQueryTitulos.setNewCurrentFieldValue("autor_id", ja.getId());
                    jDBTextFieldAutorId.setText(ja.getId());
                    jDBQueryTitulos.edit();
                    jDBQueryAutor.setSQL(qryAutor+" where id ="+ja.getId());
                    jDBQueryAutor.execQuery();
                }
            }
            @Override public void windowIconified(WindowEvent e) {}
            @Override public void windowDeiconified(WindowEvent e) {}
            @Override public void windowActivated(WindowEvent e) {}
            @Override public void windowDeactivated(WindowEvent e) {}
        });
    }//GEN-LAST:event_jButtonSelAssunto1ActionPerformed

    private void jDBQueryTitulosAfterScroll(lib.jdb.jdbquery.event.ScrollEventObject evt) {//GEN-FIRST:event_jDBQueryTitulosAfterScroll
        jDBQueryAutor.setSQL(qryAutor+" where id ="+jDBQueryTitulos.getCurrentFieldValue("autor_id"));
        jDBQueryAutor.execQuery();
        jDBQueryAssunto.setSQL(qryAssunto+" where id ="+jDBQueryTitulos.getCurrentFieldValue("assunto_id"));
        jDBQueryAssunto.execQuery();
        jLabelPosicao.setText(Integer.toString(jDBQueryTitulos.getRow())+" / ");
    }//GEN-LAST:event_jDBQueryTitulosAfterScroll

    private void jDBTextFieldAutorIdKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jDBTextFieldAutorIdKeyReleased
        if(jDBTextFieldAutorId.getText().matches("\\d")){
            jDBQueryAutor.setSQL(qryAutor+" where id ="+jDBTextFieldAutorId.getText());
            jDBQueryAutor.execQuery();
        }else{
            jDBQueryAssunto.setSQL(qryAssunto+" where id = 0");
            jDBQueryAssunto.execQuery();
        }
    }//GEN-LAST:event_jDBTextFieldAutorIdKeyReleased

    private void jDBTextFieldAssuntoIdKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jDBTextFieldAssuntoIdKeyReleased
        if(jDBTextFieldAssuntoId.getText().matches("\\d")){
            jDBQueryAssunto.setSQL(qryAssunto+" where id ="+jDBTextFieldAssuntoId.getText());
            jDBQueryAssunto.execQuery();
        }else{
            jDBQueryAssunto.setSQL(qryAssunto+" where id = 0");
            jDBQueryAssunto.execQuery();
        }            
    }//GEN-LAST:event_jDBTextFieldAssuntoIdKeyReleased

    private void jDBQueryTitulosOnSaveManually(lib.jdb.jdbquery.event.SaveManuallyEventObject evt) {//GEN-FIRST:event_jDBQueryTitulosOnSaveManually
        String msgError="" ;
        if(jDBTextFieldAutorId.getText().isEmpty()){
            msgError+="Escolha um Autor!\n";
        }
        if(jDBTextFieldAssuntoId.getText().isEmpty()){
            msgError+="Escolha um Assunto!\n";
        }
        if(jDBTextFieldTitulo.getText().isEmpty()){
            msgError+="Digite um Título!\n";
        }
        if(msgError.isEmpty()) jDBQueryTitulos.save();
        else JOptionPane.showMessageDialog(null, msgError);
    }//GEN-LAST:event_jDBQueryTitulosOnSaveManually

    private void jDBQueryTitulosPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jDBQueryTitulosPropertyChange
        jDBButtonDelete1.setEnabled(!jDBQueryTitulos.isInserting()&&!jDBQueryTitulos.isEditing());
        jDBButtonNew1.setEnabled(!jDBQueryTitulos.isInserting()&&!jDBQueryTitulos.isEditing());
        jDBButtonNext1.setEnabled(!jDBQueryTitulos.isInserting()&&!jDBQueryTitulos.isEditing()&&
                jDBQueryTitulos.getRow()<jDBQueryTitulos.getQueryQuantity());
        jDBButtonLast1.setEnabled(!jDBQueryTitulos.isInserting()&&
                                !jDBQueryTitulos.isEditing()&&
                jDBQueryTitulos.getRow()<jDBQueryTitulos.getQueryQuantity());
        jDBButtonPrevious1.setEnabled(!jDBQueryTitulos.isInserting()&&!jDBQueryTitulos.isEditing()&&
                jDBQueryTitulos.getRow()>1);
        jDBButtonFirst1.setEnabled(!jDBQueryTitulos.isInserting()&&!jDBQueryTitulos.isEditing()&&
                jDBQueryTitulos.getRow()>1);
        jDBButtonSave1.setEnabled(jDBQueryTitulos.isEditing() || jDBQueryTitulos.isInserting());
        jDBButtonCancel1.setEnabled(jDBQueryTitulos.isEditing() || jDBQueryTitulos.isInserting());
        
    }//GEN-LAST:event_jDBQueryTitulosPropertyChange

    private void jMenuItem19ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem19ActionPerformed
        jDBButtonNew1.doClick();
    }//GEN-LAST:event_jMenuItem19ActionPerformed

    private void jMenuItem20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem20ActionPerformed
        jDBButtonDelete1.doClick();
    }//GEN-LAST:event_jMenuItem20ActionPerformed

    private void jMenuItem21ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem21ActionPerformed
        jDBButtonSave1.doClick();
    }//GEN-LAST:event_jMenuItem21ActionPerformed

    private void jMenuItem22ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem22ActionPerformed
        jDBButtonCancel1.doClick();
    }//GEN-LAST:event_jMenuItem22ActionPerformed

    private void jMenuItem24ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem24ActionPerformed
        jButtonSelecionar.doClick();
    }//GEN-LAST:event_jMenuItem24ActionPerformed

    private void jMenuItem25ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem25ActionPerformed
        jButtonFechar.doClick();
    }//GEN-LAST:event_jMenuItem25ActionPerformed

    private void jMenuItem8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem8ActionPerformed
        jDBButtonFirst1.doClick();
    }//GEN-LAST:event_jMenuItem8ActionPerformed

    private void jMenuItem9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem9ActionPerformed
        jDBButtonPrevious1.doClick();
    }//GEN-LAST:event_jMenuItem9ActionPerformed

    private void jMenuItem10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem10ActionPerformed
        jDBButtonNext1.doClick();
    }//GEN-LAST:event_jMenuItem10ActionPerformed

    private void jMenuItem11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem11ActionPerformed
        jDBButtonLast1.doClick();
    }//GEN-LAST:event_jMenuItem11ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFLivros().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonFechar;
    private javax.swing.JButton jButtonSelAssunto;
    private javax.swing.JButton jButtonSelAssunto1;
    private javax.swing.JButton jButtonSelecionar;
    private lib.jdb.control.jdbbuttoncancel.JDBButtonCancel jDBButtonCancel1;
    private lib.jdb.control.jdbbuttondelete.JDBButtonDelete jDBButtonDelete1;
    private lib.jdb.control.jdbbuttonfirst.JDBButtonFirst jDBButtonFirst1;
    private lib.jdb.control.jdbbuttonlast.JDBButtonLast jDBButtonLast1;
    private lib.jdb.control.jdbbuttonnew.JDBButtonNew jDBButtonNew1;
    private lib.jdb.control.jdbbuttonnext.JDBButtonNext jDBButtonNext1;
    private lib.jdb.control.jdbbuttonprevious.JDBButtonPrevious jDBButtonPrevious1;
    private lib.jdb.control.jdbbuttonsave.JDBButtonSave jDBButtonSave1;
    private lib.jdb.control.jdbcontrolstyle.JDBControlStyle jDBControlStyle1;
    private lib.jdb.control.jdblabelcount.JDBLabelCount jDBLabelCount1;
    private lib.jdb.control.jdblookupfield.JDBLookUpField jDBLookUpField1;
    private lib.jdb.jdbquery.JDBQuery jDBQueryAssunto;
    private lib.jdb.jdbquery.JDBQuery jDBQueryAutor;
    private lib.jdb.jdbquery.JDBQuery jDBQueryTitulos;
    private lib.jdb.control.jdbtable.JDBTable jDBTable1;
    private lib.jdb.control.jdbtable.JDBTableStyle jDBTableStyle1;
    private lib.jdb.control.jdbtextarea.JDBTextArea jDBTextArea1;
    private lib.jdb.control.jdbtextfield.JDBTextField jDBTextFieldAssunto;
    private lib.jdb.control.jdbtextfield.JDBTextField jDBTextFieldAssuntoId;
    private lib.jdb.control.jdbtextfield.JDBTextField jDBTextFieldAutorId;
    private lib.jdb.control.jdbtextfield.JDBTextField jDBTextFieldTitulo;
    private lib.jdb.control.jdbtextfield.JDBTextField jDBTextFieldTitulo1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabelPosicao;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem10;
    private javax.swing.JMenuItem jMenuItem11;
    private javax.swing.JMenuItem jMenuItem19;
    private javax.swing.JMenuItem jMenuItem20;
    private javax.swing.JMenuItem jMenuItem21;
    private javax.swing.JMenuItem jMenuItem22;
    private javax.swing.JMenuItem jMenuItem24;
    private javax.swing.JMenuItem jMenuItem25;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JMenuItem jMenuItem9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPopupMenu.Separator jSeparator5;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JToolBar jToolBar2;
    private javax.swing.JToolBar jToolBar3;
    // End of variables declaration//GEN-END:variables

    public String getID(){
        return jDBQueryTitulos.getCurrentFieldValue("id");
    }
}
