
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import lib.jdb.connection.JDBConnection;
import net.sf.jasperreports.engine.JRResultSetDataSource;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.view.JasperViewer;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author vmf
 */
public class JFUsuario extends javax.swing.JFrame {
    public boolean selecionar = false;
    public final String qryUsuario = "select * from usuario where ativo = 1 ", orderby = " order by nome ";
    JFEmprestimos je=null;
    JFEmprestimoLivros jel=null;
    /**
     * Creates new form JFAluno
     */
    public JFUsuario() {
        initComponents();
        CustomTable.setDefaulttable(jDBTable1);
        jDBTable1.setFieldsTitle("nome", "Nome");
        jDBTable1.setFieldsTitle("id", "Cod.");
        jDBTable1.setFieldsTitle("rg", "RG");
        jDBTable1.setFieldsTitle("email", "E-Mail");
        jDBTable1.setFieldsTitle("celular", "Celular");
        jDBTable1.setFieldsTitle("telefone", "Telefone");
        jDBTable1.setFieldsTitle("serie", "Série");
        jDBTable1.setFieldsTitle("tipo", "Tipo");
    }
    public JFUsuario(JDBConnection jdb) {
        this();
        jDBQueryUsuario.setJDBConnection(jdb);
        jDBQueryUsuario.execQuery();
        jButtonSelecionar.setVisible(false);
    }
    public JFUsuario(JDBConnection jdb, boolean selecionar) {
        this();
        jDBQueryUsuario.setJDBConnection(jdb);
        jDBQueryUsuario.execQuery();
        jButtonSelecionar.setVisible(selecionar);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDBQueryUsuario = new lib.jdb.jdbquery.JDBQuery();
        jDBControlStyle1 = new lib.jdb.control.jdbcontrolstyle.JDBControlStyle();
        jDBTableStyle1 = new lib.jdb.control.jdbtable.JDBTableStyle();
        jDBTextField1 = new lib.jdb.control.jdbtextfield.JDBTextField();
        jLabel1 = new javax.swing.JLabel();
        jDBTextField2 = new lib.jdb.control.jdbtextfield.JDBTextField();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jDBTable1 = new lib.jdb.control.jdbtable.JDBTable();
        jDBTextField3 = new lib.jdb.control.jdbtextfield.JDBTextField();
        jLabel3 = new javax.swing.JLabel();
        jDBTextField4 = new lib.jdb.control.jdbtextfield.JDBTextField();
        jLabel4 = new javax.swing.JLabel();
        jDBTextField5 = new lib.jdb.control.jdbtextfield.JDBTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jDBTextField6 = new lib.jdb.control.jdbtextfield.JDBTextField();
        jLabel7 = new javax.swing.JLabel();
        jDBTextField7 = new lib.jdb.control.jdbtextfield.JDBTextField();
        jLabel8 = new javax.swing.JLabel();
        jDBTextField8 = new lib.jdb.control.jdbtextfield.JDBTextField();
        jLabel9 = new javax.swing.JLabel();
        jDBComboBox1 = new lib.jdb.control.jdbcombobox.JDBComboBox();
        jLabel10 = new javax.swing.JLabel();
        jDBTextField9 = new lib.jdb.control.jdbtextfield.JDBTextField();
        jToolBar1 = new javax.swing.JToolBar();
        jDBButtonCancel1 = new lib.jdb.control.jdbbuttoncancel.JDBButtonCancel();
        jDBButtonDelete1 = new lib.jdb.control.jdbbuttondelete.JDBButtonDelete();
        jDBButtonSave1 = new lib.jdb.control.jdbbuttonsave.JDBButtonSave();
        jDBButtonNew1 = new lib.jdb.control.jdbbuttonnew.JDBButtonNew();
        jToolBar2 = new javax.swing.JToolBar();
        jDBButtonFirst1 = new lib.jdb.control.jdbbuttonfirst.JDBButtonFirst();
        jDBButtonPrevious1 = new lib.jdb.control.jdbbuttonprevious.JDBButtonPrevious();
        jLabelPosicao = new javax.swing.JLabel();
        jDBLabelCount1 = new lib.jdb.control.jdblabelcount.JDBLabelCount();
        jDBButtonNext1 = new lib.jdb.control.jdbbuttonnext.JDBButtonNext();
        jDBButtonLast1 = new lib.jdb.control.jdbbuttonlast.JDBButtonLast();
        jToolBar3 = new javax.swing.JToolBar();
        jButtonSelecionar = new javax.swing.JButton();
        jButtonFechar = new javax.swing.JButton();
        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu7 = new javax.swing.JMenu();
        jMenuItem19 = new javax.swing.JMenuItem();
        jMenuItem20 = new javax.swing.JMenuItem();
        jMenuItem21 = new javax.swing.JMenuItem();
        jMenuItem22 = new javax.swing.JMenuItem();
        jSeparator5 = new javax.swing.JPopupMenu.Separator();
        jMenuItem24 = new javax.swing.JMenuItem();
        jMenuItem25 = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem6 = new javax.swing.JMenuItem();
        jSeparator3 = new javax.swing.JPopupMenu.Separator();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        jMenuItem8 = new javax.swing.JMenuItem();
        jMenuItem9 = new javax.swing.JMenuItem();
        jMenuItem10 = new javax.swing.JMenuItem();
        jMenuItem11 = new javax.swing.JMenuItem();

        jDBQueryUsuario.setSQL("select * from usuario order by nome");
        jDBQueryUsuario.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                jDBQueryUsuarioPropertyChange(evt);
            }
        });
        jDBQueryUsuario.addScrollEventListener(new lib.jdb.jdbquery.event.ScrollEventListener() {
            public void beforeScroll(lib.jdb.jdbquery.event.ScrollEventObject evt) {
            }
            public void afterScroll(lib.jdb.jdbquery.event.ScrollEventObject evt) {
                jDBQueryUsuarioAfterScroll(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Usuários");

        jDBTextField1.setJDBQuery(jDBQueryUsuario);
        jDBTextField1.setFieldName("nome");
        jDBTextField1.setjDBControlStyle(jDBControlStyle1);

        jLabel1.setText("Nome");

        jDBTextField2.setJDBQuery(jDBQueryUsuario);
        jDBTextField2.setFieldName("rg");
        jDBTextField2.setjDBControlStyle(jDBControlStyle1);

        jLabel2.setText("RG");

        jDBTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jDBTable1.setJDBQuery(jDBQueryUsuario);
        jDBTable1.setEditable(false);
        jDBTable1.setInvisibleFields("num bairro rua pendencia ativo");
        jDBTable1.setjDBTableStyle(jDBTableStyle1);
        jScrollPane1.setViewportView(jDBTable1);

        jDBTextField3.setJDBQuery(jDBQueryUsuario);
        jDBTextField3.setFieldName("rua");
        jDBTextField3.setjDBControlStyle(jDBControlStyle1);

        jLabel3.setText("Rua");

        jDBTextField4.setJDBQuery(jDBQueryUsuario);
        jDBTextField4.setFieldName("num");
        jDBTextField4.setjDBControlStyle(jDBControlStyle1);

        jLabel4.setText("Número");

        jDBTextField5.setJDBQuery(jDBQueryUsuario);
        jDBTextField5.setFieldName("bairro");
        jDBTextField5.setjDBControlStyle(jDBControlStyle1);

        jLabel5.setText("Bairro");

        jLabel6.setText("E-Mail");

        jDBTextField6.setJDBQuery(jDBQueryUsuario);
        jDBTextField6.setFieldName("email");
        jDBTextField6.setjDBControlStyle(jDBControlStyle1);

        jLabel7.setText("Telefone");

        jDBTextField7.setJDBQuery(jDBQueryUsuario);
        jDBTextField7.setFieldName("telefone");
        jDBTextField7.setjDBControlStyle(jDBControlStyle1);

        jLabel8.setText("Celular");

        jDBTextField8.setJDBQuery(jDBQueryUsuario);
        jDBTextField8.setFieldName("celular");
        jDBTextField8.setjDBControlStyle(jDBControlStyle1);

        jLabel9.setText("Tipo ");

        jDBComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Aluno", "Professor", "Funcionário" }));
        jDBComboBox1.setJDBQuery(jDBQueryUsuario);
        jDBComboBox1.setFieldName("tipo");
        jDBComboBox1.setjDBControlStyle(jDBControlStyle1);
        jDBComboBox1.setName(""); // NOI18N

        jLabel10.setText("Série");

        jDBTextField9.setJDBQuery(jDBQueryUsuario);
        jDBTextField9.setFieldName("serie");
        jDBTextField9.setjDBControlStyle(jDBControlStyle1);

        jToolBar1.setRollover(true);

        jDBButtonCancel1.setJDBQuery(jDBQueryUsuario);
        jDBButtonCancel1.setFocusable(false);
        jDBButtonCancel1.setHorizontalTextPosition(0);
        jDBButtonCancel1.setText("");
        jDBButtonCancel1.setToolTipText("Cancelar");
        jDBButtonCancel1.setVerticalTextPosition(3);
        jToolBar1.add(jDBButtonCancel1);

        jDBButtonDelete1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/del.png"))); // NOI18N
        jDBButtonDelete1.setJDBQuery(jDBQueryUsuario);
        jDBButtonDelete1.setFocusable(false);
        jDBButtonDelete1.setHorizontalTextPosition(0);
        jDBButtonDelete1.setText("");
        jDBButtonDelete1.setToolTipText("Excluir");
        jDBButtonDelete1.setVerticalTextPosition(3);
        jToolBar1.add(jDBButtonDelete1);

        jDBButtonSave1.setJDBQuery(jDBQueryUsuario);
        jDBButtonSave1.setFocusable(false);
        jDBButtonSave1.setHorizontalTextPosition(0);
        jDBButtonSave1.setText("");
        jDBButtonSave1.setToolTipText("Salvar");
        jDBButtonSave1.setVerticalTextPosition(3);
        jToolBar1.add(jDBButtonSave1);

        jDBButtonNew1.setJDBQuery(jDBQueryUsuario);
        jDBButtonNew1.setFocusable(false);
        jDBButtonNew1.setHorizontalTextPosition(0);
        jDBButtonNew1.setText("");
        jDBButtonNew1.setToolTipText("Novo");
        jDBButtonNew1.setVerticalTextPosition(3);
        jToolBar1.add(jDBButtonNew1);

        jToolBar2.setRollover(true);

        jDBButtonFirst1.setJDBQuery(jDBQueryUsuario);
        jDBButtonFirst1.setFocusable(false);
        jDBButtonFirst1.setHorizontalTextPosition(0);
        jDBButtonFirst1.setText("");
        jDBButtonFirst1.setVerticalTextPosition(3);
        jToolBar2.add(jDBButtonFirst1);

        jDBButtonPrevious1.setJDBQuery(jDBQueryUsuario);
        jDBButtonPrevious1.setFocusable(false);
        jDBButtonPrevious1.setHorizontalTextPosition(0);
        jDBButtonPrevious1.setText("");
        jDBButtonPrevious1.setVerticalTextPosition(3);
        jToolBar2.add(jDBButtonPrevious1);

        jLabelPosicao.setText("0 / ");
        jToolBar2.add(jLabelPosicao);

        jDBLabelCount1.setjDBQuery(jDBQueryUsuario);
        jToolBar2.add(jDBLabelCount1);

        jDBButtonNext1.setJDBQuery(jDBQueryUsuario);
        jDBButtonNext1.setFocusable(false);
        jDBButtonNext1.setHorizontalTextPosition(0);
        jDBButtonNext1.setText("");
        jDBButtonNext1.setVerticalTextPosition(3);
        jToolBar2.add(jDBButtonNext1);

        jDBButtonLast1.setJDBQuery(jDBQueryUsuario);
        jDBButtonLast1.setFocusable(false);
        jDBButtonLast1.setHorizontalTextPosition(0);
        jDBButtonLast1.setText("");
        jDBButtonLast1.setVerticalTextPosition(3);
        jToolBar2.add(jDBButtonLast1);

        jToolBar3.setRollover(true);

        jButtonSelecionar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/confirm.png"))); // NOI18N
        jButtonSelecionar.setToolTipText("Ok");
        jButtonSelecionar.setFocusable(false);
        jButtonSelecionar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonSelecionar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButtonSelecionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSelecionarActionPerformed(evt);
            }
        });
        jToolBar3.add(jButtonSelecionar);

        jButtonFechar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cancel.png"))); // NOI18N
        jButtonFechar.setToolTipText("Fechar");
        jButtonFechar.setFocusable(false);
        jButtonFechar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonFechar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButtonFechar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonFecharActionPerformed(evt);
            }
        });
        jToolBar3.add(jButtonFechar);

        jMenu7.setMnemonic('a');
        jMenu7.setText("Arquivo");

        jMenuItem19.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_N, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem19.setMnemonic('n');
        jMenuItem19.setText("Novo");
        jMenuItem19.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem19ActionPerformed(evt);
            }
        });
        jMenu7.add(jMenuItem19);

        jMenuItem20.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_E, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem20.setMnemonic('e');
        jMenuItem20.setText("Excluir");
        jMenuItem20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem20ActionPerformed(evt);
            }
        });
        jMenu7.add(jMenuItem20);

        jMenuItem21.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem21.setMnemonic('s');
        jMenuItem21.setText("Salvar");
        jMenuItem21.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem21ActionPerformed(evt);
            }
        });
        jMenu7.add(jMenuItem21);

        jMenuItem22.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem22.setMnemonic('c');
        jMenuItem22.setText("Cancelar");
        jMenuItem22.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem22ActionPerformed(evt);
            }
        });
        jMenu7.add(jMenuItem22);
        jMenu7.add(jSeparator5);

        jMenuItem24.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_O, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem24.setMnemonic('o');
        jMenuItem24.setText("Ok");
        jMenuItem24.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem24ActionPerformed(evt);
            }
        });
        jMenu7.add(jMenuItem24);

        jMenuItem25.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem25.setMnemonic('f');
        jMenuItem25.setText("Fechar");
        jMenuItem25.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem25ActionPerformed(evt);
            }
        });
        jMenu7.add(jMenuItem25);

        jMenuBar2.add(jMenu7);

        jMenu1.setMnemonic('p');
        jMenu1.setText("Pesquisar");
        jMenu1.setToolTipText("");

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_N, java.awt.event.InputEvent.ALT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem1.setMnemonic('n');
        jMenuItem1.setText("Nome");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuItem2.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_R, java.awt.event.InputEvent.ALT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem2.setText("RG");
        jMenuItem2.setToolTipText("r");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuItem3.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.ALT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem3.setText("Código");
        jMenuItem3.setToolTipText("c");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem3);
        jMenu1.add(jSeparator1);

        jMenuBar2.add(jMenu1);

        jMenu3.setMnemonic('e');
        jMenu3.setText("Empréstimos");

        jMenuItem6.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_E, java.awt.event.InputEvent.ALT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem6.setMnemonic('n');
        jMenuItem6.setText("Novo");
        jMenuItem6.setToolTipText("");
        jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem6ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem6);
        jMenu3.add(jSeparator3);

        jMenuItem4.setMnemonic('t');
        jMenuItem4.setText("Todos");
        jMenuItem4.setToolTipText("");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem4);

        jMenuBar2.add(jMenu3);

        jMenu2.setText("Relatórios");

        jMenuItem5.setText("Histórico de Empréstimos");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem5);

        jMenuBar2.add(jMenu2);

        jMenu5.setMnemonic('n');
        jMenu5.setText("Navegação");

        jMenuItem8.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_LEFT, java.awt.event.InputEvent.SHIFT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem8.setText("Primeiro");
        jMenuItem8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem8ActionPerformed(evt);
            }
        });
        jMenu5.add(jMenuItem8);

        jMenuItem9.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_LEFT, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem9.setText("Anterior");
        jMenuItem9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem9ActionPerformed(evt);
            }
        });
        jMenu5.add(jMenuItem9);

        jMenuItem10.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_RIGHT, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem10.setText("Próximo");
        jMenuItem10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem10ActionPerformed(evt);
            }
        });
        jMenu5.add(jMenuItem10);

        jMenuItem11.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_RIGHT, java.awt.event.InputEvent.SHIFT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem11.setText("Ultimo");
        jMenuItem11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem11ActionPerformed(evt);
            }
        });
        jMenu5.add(jMenuItem11);

        jMenuBar2.add(jMenu5);

        setJMenuBar(jMenuBar2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(jDBTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jDBTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jDBComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel9))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jDBTextField9, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel10)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6)
                                    .addComponent(jDBTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel7)
                                    .addComponent(jDBTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel8)
                                    .addComponent(jDBTextField8, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jDBTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(jDBTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5)
                                    .addComponent(jDBTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 13, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addComponent(jToolBar2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jToolBar3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jToolBar2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jToolBar3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel1)
                                .addComponent(jLabel2))
                            .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jDBTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jDBTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jDBComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jDBTextField9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(14, 14, 14))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addGap(51, 51, 51)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jDBTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jDBTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jDBTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jDBTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jDBTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jDBTextField8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonSelecionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSelecionarActionPerformed
        selecionar=true;
        this.dispose();
    }//GEN-LAST:event_jButtonSelecionarActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        String nome = JOptionPane.showInputDialog("Digite o nome");
        jDBQueryUsuario.setSQL(qryUsuario+" and nome like '%"+nome+"%'"+orderby);
        jDBQueryUsuario.execQuery();
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        String rg = JOptionPane.showInputDialog("Digite o rg");
        jDBQueryUsuario.setSQL(qryUsuario+" and rg = '"+rg+"'"+orderby);
        jDBQueryUsuario.execQuery();
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
       JFEmprestimos je = new JFEmprestimos(jDBQueryUsuario.getJDBConnection(), jDBQueryUsuario.getCurrentFieldValue("id"));
       je.show();
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jButtonFecharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonFecharActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButtonFecharActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        String nome = JOptionPane.showInputDialog("Digite o Código");
        jDBQueryUsuario.setSQL(qryUsuario+" and id ="+nome+orderby);
        jDBQueryUsuario.execQuery();
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        Conexao con;
        ResultSet rs;
        con = new Conexao(jDBQueryUsuario.getJDBConnection().getConnection());
        try{
            con.Preparar("select e.id as \"Cod\", e.data as \"Data\", el.prazo_devolucao as \"Prazo\", el.data_devolucao as \"Devolução\", t.titulo as \"Título\" from emprestimo e " +
                " inner join emprestimo_livros el on e.id = el.emprestimo_id\n" +
                " inner join livro l on l.id = el.livro_id " +
                " inner join titulo t on t.id = l.titulo_id where e.usuario_id="+jDBQueryUsuario.getCurrentFieldValue("id")+
                " order by e.data desc ");
            rs = con.RetornaDados(new Object[]{});
            JasperPrint jp = JasperFillManager.fillReport(Principal.relPath+"RelatorioHistoricoEmprestimos.jasper", null, 
                    new JRResultSetDataSource(rs));
             JasperViewer.viewReport(jp,false);
        }
        catch(Exception e){ JOptionPane.showMessageDialog(null, e);}
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem6ActionPerformed
        if(jel!=null)jel.dispose();
        jel = new JFEmprestimoLivros(jDBQueryUsuario.getJDBConnection(),
            jDBQueryUsuario.getCurrentFieldValueAsInteger("id"));
        jel.show();
    }//GEN-LAST:event_jMenuItem6ActionPerformed

    private void jDBQueryUsuarioAfterScroll(lib.jdb.jdbquery.event.ScrollEventObject evt) {//GEN-FIRST:event_jDBQueryUsuarioAfterScroll
        jLabelPosicao.setText(Integer.toString(jDBQueryUsuario.getRow())+" / ");
    }//GEN-LAST:event_jDBQueryUsuarioAfterScroll

    private void jDBQueryUsuarioPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jDBQueryUsuarioPropertyChange
        jDBButtonDelete1.setEnabled(!jDBQueryUsuario.isInserting()&&!jDBQueryUsuario.isEditing());
        jDBButtonNew1.setEnabled(!jDBQueryUsuario.isInserting()&&!jDBQueryUsuario.isEditing());
        jDBButtonNext1.setEnabled(!jDBQueryUsuario.isInserting()&&!jDBQueryUsuario.isEditing()&&
                jDBQueryUsuario.getRow()<jDBQueryUsuario.getQueryQuantity());
        jDBButtonLast1.setEnabled(!jDBQueryUsuario.isInserting()&&
                                !jDBQueryUsuario.isEditing()&&
                jDBQueryUsuario.getRow()<jDBQueryUsuario.getQueryQuantity());
        jDBButtonPrevious1.setEnabled(!jDBQueryUsuario.isInserting()&&!jDBQueryUsuario.isEditing()&&
                jDBQueryUsuario.getRow()>1);
        jDBButtonFirst1.setEnabled(!jDBQueryUsuario.isInserting()&&!jDBQueryUsuario.isEditing()&&
                jDBQueryUsuario.getRow()>1);
        jDBButtonSave1.setEnabled(jDBQueryUsuario.isEditing() || jDBQueryUsuario.isInserting());
        jDBButtonCancel1.setEnabled(jDBQueryUsuario.isEditing() || jDBQueryUsuario.isInserting());
        
    }//GEN-LAST:event_jDBQueryUsuarioPropertyChange

    private void jMenuItem19ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem19ActionPerformed
        jDBButtonNew1.doClick();
    }//GEN-LAST:event_jMenuItem19ActionPerformed

    private void jMenuItem20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem20ActionPerformed
        jDBButtonDelete1.doClick();
    }//GEN-LAST:event_jMenuItem20ActionPerformed

    private void jMenuItem21ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem21ActionPerformed
        jDBButtonSave1.doClick();
    }//GEN-LAST:event_jMenuItem21ActionPerformed

    private void jMenuItem22ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem22ActionPerformed
        jDBButtonCancel1.doClick();
    }//GEN-LAST:event_jMenuItem22ActionPerformed

    private void jMenuItem24ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem24ActionPerformed
        jButtonSelecionar.doClick();
    }//GEN-LAST:event_jMenuItem24ActionPerformed

    private void jMenuItem25ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem25ActionPerformed
        jButtonFechar.doClick();
    }//GEN-LAST:event_jMenuItem25ActionPerformed

    private void jMenuItem8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem8ActionPerformed
        jDBButtonFirst1.doClick();
    }//GEN-LAST:event_jMenuItem8ActionPerformed

    private void jMenuItem9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem9ActionPerformed
        jDBButtonPrevious1.doClick();
    }//GEN-LAST:event_jMenuItem9ActionPerformed

    private void jMenuItem10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem10ActionPerformed
        jDBButtonNext1.doClick();
    }//GEN-LAST:event_jMenuItem10ActionPerformed

    private void jMenuItem11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem11ActionPerformed
        jDBButtonLast1.doClick();
    }//GEN-LAST:event_jMenuItem11ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFUsuario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonFechar;
    private javax.swing.JButton jButtonSelecionar;
    private lib.jdb.control.jdbbuttoncancel.JDBButtonCancel jDBButtonCancel1;
    private lib.jdb.control.jdbbuttondelete.JDBButtonDelete jDBButtonDelete1;
    private lib.jdb.control.jdbbuttonfirst.JDBButtonFirst jDBButtonFirst1;
    private lib.jdb.control.jdbbuttonlast.JDBButtonLast jDBButtonLast1;
    private lib.jdb.control.jdbbuttonnew.JDBButtonNew jDBButtonNew1;
    private lib.jdb.control.jdbbuttonnext.JDBButtonNext jDBButtonNext1;
    private lib.jdb.control.jdbbuttonprevious.JDBButtonPrevious jDBButtonPrevious1;
    private lib.jdb.control.jdbbuttonsave.JDBButtonSave jDBButtonSave1;
    private lib.jdb.control.jdbcombobox.JDBComboBox jDBComboBox1;
    private lib.jdb.control.jdbcontrolstyle.JDBControlStyle jDBControlStyle1;
    private lib.jdb.control.jdblabelcount.JDBLabelCount jDBLabelCount1;
    private lib.jdb.jdbquery.JDBQuery jDBQueryUsuario;
    private lib.jdb.control.jdbtable.JDBTable jDBTable1;
    private lib.jdb.control.jdbtable.JDBTableStyle jDBTableStyle1;
    private lib.jdb.control.jdbtextfield.JDBTextField jDBTextField1;
    private lib.jdb.control.jdbtextfield.JDBTextField jDBTextField2;
    private lib.jdb.control.jdbtextfield.JDBTextField jDBTextField3;
    private lib.jdb.control.jdbtextfield.JDBTextField jDBTextField4;
    private lib.jdb.control.jdbtextfield.JDBTextField jDBTextField5;
    private lib.jdb.control.jdbtextfield.JDBTextField jDBTextField6;
    private lib.jdb.control.jdbtextfield.JDBTextField jDBTextField7;
    private lib.jdb.control.jdbtextfield.JDBTextField jDBTextField8;
    private lib.jdb.control.jdbtextfield.JDBTextField jDBTextField9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelPosicao;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem10;
    private javax.swing.JMenuItem jMenuItem11;
    private javax.swing.JMenuItem jMenuItem19;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem20;
    private javax.swing.JMenuItem jMenuItem21;
    private javax.swing.JMenuItem jMenuItem22;
    private javax.swing.JMenuItem jMenuItem24;
    private javax.swing.JMenuItem jMenuItem25;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JMenuItem jMenuItem9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator3;
    private javax.swing.JPopupMenu.Separator jSeparator5;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JToolBar jToolBar2;
    private javax.swing.JToolBar jToolBar3;
    // End of variables declaration//GEN-END:variables

    public String getId(){
        return jDBQueryUsuario.getCurrentFieldValue("id");
    }
}
